### PR TITLE
Remove ReadonlyResolveFieldContext

### PR DESCRIPTION
**Pull request by Shane32**
This PR makes ExecutionNode implement IResolveFieldContext, so an instance of ReadonlyResolveFieldContext is not required, saving an object allocation per resolver.  Doesn't really enhance performance, although the number of object allocations decrease notably as can be seen in the GC stats below.  Memory doesn't change much due to the previous enhancement of the ReadonlyResolveFieldContext over the prior ResolveFieldContext class.

Just a thought - ok to merge or close.

```
// * Summary *

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-7740X CPU 4.30GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
  DefaultJob : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT


*** BEFORE ***

|        Method |        Mean |     Error |    StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|-------------- |------------:|----------:|----------:|---------:|--------:|------:|----------:|
| Introspection | 1,503.10 us | 19.721 us | 17.483 us | 189.4531 | 60.5469 |     - | 835.56 KB |
|          Hero |    34.32 us |  0.639 us |  0.566 us |   6.1035 |  0.0610 |     - |   25.1 KB |

*** AFTER ***

|        Method |        Mean |     Error |    StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|-------------- |------------:|----------:|----------:|---------:|--------:|------:|----------:|
| Introspection | 1,496.35 us | 19.890 us | 18.605 us | 171.8750 | 48.8281 |     - | 807.63 KB |
|          Hero |    34.44 us |  0.597 us |  0.558 us |   6.1035 |       - |     - |  25.05 KB |
```

### CODE REVIEW

**Comment by sungam3r** [comment]
I am familiar with such optimization methods and I have an ambiguous attitude towards them. On the one hand, the number of entities that work in close interconnection is reduced. It really saves memory. On the other hand, combining entities into one can affect code clarity and problems during project evolution.

 I looked at the code briefly and will still watch it again. So far my opinion is 50/50.

**Comment by sungam3r** [comment]
Just noticed - `X64 RyuJIT` in your test, ` X86 RyuJIT` in my. Did you change the test settings?

**Comment by Shane32** [comment]
Nope.  I don't know why, but it's always been that way.  My PC always tests in X64 and your baseline comparison tests are always X86.

**Comment by Shane32** [comment]
The last time I did some testing, I found that someone had changed the default tests to run speed comparisons with the different serializer packages, so I did have to reconfigure it to run the Introspection and Hero tests.

**Comment by Shane32** [comment]
@sungam3r Let me know your general thoughts on this PR.  I'm happy to close it or update it, either way.  I doubt this will provide any meaningful benefit for anyone, even if it is a measurable speed increase.

**Comment by sungam3r** [comment]
The difference in performance is not that big. I have a suspicion that such a merge might cause then problems for us with DI evolution after green light to #1730. There probably will be new `IResolveFieldContext` implementations. As I said earlier
> On the other hand, combining entities into one can affect code clarity and problems during project evolution.

Closing.

**Pull request closed without merging**
