### PR TITLE
Adds API Approval tests

### PR DESCRIPTION
**Pull request by sungam3r**
Adds a mechanism for controlled change of public api:
 
https://github.com/JakeGinnivan/ApiApprover

### CODE REVIEW

**Comment by sungam3r** [comment]
Something unusual with appveyor build, locally tests pass.

**Comment by joemcbride** [comment]
My first guess would be related to the line ending issue. https://github.com/JakeGinnivan/ApiApprover/pull/76

**Comment by sungam3r** [comment]
I'm sure line endings is another story.

**Comment by sungam3r** [comment]
@joemcbride I finally figured it out. Indeed, the point is the configuration with which the tests are run. I added a new test project and adjusted test.dotnet.js file so that it forces it to run with the Debug configuration. I have no experience configuring AppVeyor CI and did everything by intuition. Feel free to fix me if it should be done another way.

**Pull request merged**
