### PR TITLE
Adding complexity and query depth analysis

### PR DESCRIPTION
**Pull request by dNetGuru**
This is a PR for #185.

### CODE REVIEW

**Comment by dNetGuru** [comment]
@joemcbride Since DocumentExecuter.ExecuteAsync is quite central to this library I refrained from editing its signature.
The user should be able to specify a maximum depth for queries, a maximum complexity along with a heurisitc guess for the average number of entities returned for each field (this is passed to ComplexityAnalyzer's ctor).

For now I'm just printing the complexity and depth to the debug console.

The ComplexityMap dictionary has a detailed account of each AST node with its calculated complexity. We can use this to show the most complex nodes to the user (when throwing an error etc.)

**Comment by dNetGuru** [comment]
Testing the completed concept: https://github.com/dNetGuru/graphql-dotnet/blob/master/src/GraphQL.Tests/Complexity/ComplexityValidationTests.cs

**Comment by dNetGuru** [comment]
@joemcbride let me know what you think!

**Comment by dNetGuru** [comment]
Fragments are now supported. All tests passing!

**Comment by joemcbride** [comment]
I don't have any strong opinions on the algorithm so I think this is looking great.  I did however just merge a bunch of changes that created some merge conflicts for you.

I added a new overload to `DocumentExecutor` which allows you to pass a configuration object to the executor.  This will help us move away from adding just another optional parameter to the execution method.  I would like to add that `ComplexityConfiguration` to that `ExecutionOptions` class instead of adding it as an optional parameter.

Sorry about creating conflicts for you!  I think this will be better in the long run though.  Thanks for this work!

**Comment by joemcbride** [comment]
New execution pattern looks something like this:

```csharp
var result = await _executer.ExecuteAsync(_ =>
{
    _.Schema = _schema;
    _.Query = queryToExecute;
    _.OperationName = query.OperationName;
    _.Inputs = inputs;
    _.Complexity = ... /// your new config

    _.FieldMiddleware.Use<InstrumentFieldsMiddleware>();

}).ConfigureAwait(false);
```

**Comment by dNetGuru** [comment]
No problem. I'll pull the new changes and fix any conflicts before this weekend

**Comment by dNetGuru** [comment]
I really like the new outline of the library! Awesome work.

I ended up having some spare time so I ported the changes and all builds/tests are passing now. I did also call the Metric.Subject (to be consistent with the rest of the file).

It doesn't take more than a millisecond to run the complexity heuristics (unless you are in debug mode where calls to Debug.WriteLine in a loop would take ~30ms here https://github.com/graphql-dotnet/graphql-dotnet/pull/209/files#diff-c2e673b2d799880c33583cfba1f798daR37).

Let me know what you think.

If you could hold off on merging this until this weekend that would be great. I might add a few things and fine tune this a bit more.

**Comment by dNetGuru** [comment]
Okay @joemcbride, I'm finished working on this! Merge at will.

I added some more logic to handle complexity changes when limits are imposed during pagination using these convenstions: https://facebook.github.io/relay/graphql/connections.htm#sec-Pagination-algorith.

I'll try to write up some docs on this when I get the chance,
Also if there are any bugs, questions etc. about my contributions please let me know I'll try to provide a timely fix.

**Comment by dNetGuru** [comment]
I see that there is a docs branch was added. Should I write the documentation within this PR or should I make a PR for the docs branch?

**Comment by dNetGuru** [comment]
All tests are passing, everything seems to be in order. @joemcbride let me know if I need to change anything.

**Comment by joemcbride** [comment]
This looks good to me, I like the updates you added.  I did have concerns about performance but those numbers look good to me.  Thanks again for this addition!

**Comment by joemcbride** [comment]
Closes #185

**Pull request merged**
