### PR TITLE
update refs

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by sungam3r** [comment]
There might be people who have problems after raising the minimum required version of packages.  I myself am not against it.

**Comment by SimonCropp** [comment]
> There might be people who have problems after raising the minimum required version of packages

i never understood that logic. i think packages should release with the current stable of dependencies at every release. for comparison, when adding a dependency, you always pick the latest stable, so if u dont make concessions for the first release with a dependency, i dont understand why you would on the subsequent releases

**Comment by SimonCropp** [comment]
and i would prefer to optimise to better support for people who actively keep their software up-to-date, rather than optimise for people who dont

**Comment by sungam3r** [comment]
The logic is to allow users to use wider range of compatible versions. They may have incompatibility issues with other parts of their software. Loosening requirements for minimum versions of dependencies may help them to choose - just keep older version or upgrade explicitly adding the same dependency but with higher version.

**Comment by SimonCropp** [comment]
but they can also explicitly use an older version of a dependency

**Comment by sungam3r** [comment]
No. Only specified in nuspec or higher. Nuget doesn't allow to use lower version.

**Comment by SimonCropp** [comment]
i just checked, and `<NoWarn>NU1605;NU1603</NoWarn>` still works to force a lower version

**Comment by sungam3r** [comment]
Wow, ок.

**Pull request merged**
