### PR TITLE
Input errors

### PR DESCRIPTION
**Pull request by jquense**
Adds some more detil to these errors. I've found it fairly frustrating to debug mutation inputs with the existing ones :)

### CODE REVIEW

**Comment by jquense** [comment]
oops with the merge commit, one second

**Comment by joemcbride** [comment]
👍  Will merge once you have that fixed up.

**Comment by jquense** [comment]
:+1: should be gtg, wouldn't mind a quick release if you have a moment as well ;) (no worries if not)

**Comment by joemcbride** [comment]
AppVeyor seems to not be happy today ... going to pull it down locally.

**Comment by joemcbride** [comment]
Merged and got the version bumped, waiting game on AppVeyor now ... if it doesn't clear I'll get a manual release out.

**Comment by jquense** [comment]
:bowing_man: thanks so much!

**Comment by joemcbride** [comment]
Finally got a build out. https://www.nuget.org/packages/GraphQL/0.14.5.654

**Pull request merged**
