### PR TITLE
Expose Schema.CreateTypesLookup and related members as protected

### PR DESCRIPTION
**Pull request by Shane32**
Possible fix for #1952 

Purpose:
- Allow changing behavior of built-in scalars such as `StringGraphType`

Challenges:
- Built-in scalar behaviors should probably be retained for introspection types

### CODE REVIEW

**Comment by Shane32** [comment]
The problem with this sample is that changing the built-in scalars affects the built-in introspection types, which is not the intent of the sample.  Further, the test would not work correctly at first because the introspection types were `static`, so the `GraphTypesLookup` class would 'lock onto' the `StringGraphType` previously used in the static introspection types, ignoring the `BuiltInScalars` protected member.  This wouldn't matter if you didn't use more than one schema in your codebase, but it's noteworthy.

I do like where this is heading, but it would seem to me that this requires some further review before any change is made.

**Comment by sungam3r** [comment]
Wow. Wait a minute. Why static??? I remember that I changed them to be instance fields. https://github.com/graphql-dotnet/graphql-dotnet/pull/1887#issuecomment-708261218 I don't understand yet what happened. They are really static.

**Comment by sungam3r** [comment]
Some kind of nonsense has happened. Either I lost the last commit, or I am hallucinating.

**Comment by sungam3r** [comment]
#1954

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/3.1.1

**Comment by Shane32** [comment]
`GraphTypesLookup` is renamed `SchemaTypes` and is mostly private as of #2183 so closing this PR.  We can revisit this if there is a need for the class to become more extensible.

**Pull request closed without merging**
