### PR TITLE
Spikes on vNext

### PR DESCRIPTION
**Pull request by joemcbride**
A few sample usages.  Notice no inheritance for `Schema` types!

```
var schema = new GraphQL2.StarWarsSchema(new GraphQL2.StarWarsData());
var engine = GraphQLEngine.For(schema);
var query = @"query aQuery { hero { id } }";
var result = await engine.ExecuteAsync(query);
```

```
public class StarWarsSchema
{
    public GraphQLObjectType Query { get; set; }
    public GraphQLObjectType Mutation { get; set; }

    public StarWarsSchema(IStarWarsData data)
    {
        var episodeEnum = GraphQLEnumType.For<Episodes>(_ =>
        {
            _.Name = "Episode";
            _.Description = "One of the films in the Star Wars Trilogy.";
            _.Value("NEWHOPE", Episodes.NEWHOPE, "Released in 1977.");
            _.Value("EMPIRE", Episodes.EMPIRE, "Released in 1980.");
            _.Value("JEDI", Episodes.JEDI, "Released in 1983.");
        });

        var episodeEnum2 = GraphQLEnumType.For<Episodes>();

        var characterType = GraphQLInterfaceType<ICharacter>.For(_ =>
        {
            _.Field(x => x.Id);
            _.Field("name", x => x.Name);
            _.Field("friends", new GraphQLList(new GraphQLTypeReference(_.Name)));
            _.Field("appearsIn", new GraphQLList(episodeEnum));
        });

        var droidType = GraphQLObjectType<Droid>.For(_ =>
        {
            _.Field(x => x.Name);
            _.Field(
                name: "friends",
                type: new GraphQLList(characterType),
                resolve: (droid, context) => data.FriendsForAsync(droid.Id));
            _.Interface(characterType);
            _.IsOfType = value => value is Droid;
        });

        var humanType = GraphQLObjectType<Human>.For(_ =>
        {
            _.Field(x => x.Name);
            _.Field(
                name: "friends",
                type: new GraphQLList(characterType),
                resolve: (human, context) => data.FriendsForAsync(human.Id));
            _.Interface(characterType);
            _.IsOfType = value => value is Human;
        });

        var inputType = GraphQLInputObjectType.For(_ =>
        {
            _.Field<string>("fred");
        });

        var inputType2 = GraphQLInputObjectType.For<ICharacter>(_ =>
        {
            _.Field(x => x.Id);
        });

        var queryRoot = GraphQLObjectType.For(_ =>
        {
            _.Name = "Root";
            _.Field(
                "hero",
                characterType,
                resolve: context => data.DroidWithIdAsync("3"));
            _.Field(
                "droid",
                new GraphQLList(droidType),
                args: args => args.Argument<string>("id", "Id of the droid."),
                resolve: context => data.DroidWithIdAsync(context.Argument<string>("id")));
            _.Field(f =>
            {
                f.Name = "human";
                f.Type = new GraphQLList(humanType);
                f.Type = humanType;
                f.Resolve = new FuncFieldResolver<Human>(context => data.HumanWithId(context.Argument<string>("id")));
                f.Argument<string>("id", "Id of the human.");
            });
        });

        Query = queryRoot;
    }
}
```

### CODE REVIEW

**Comment by tlil87** [comment]
:+1: Like it - will take a closer look when I'm back from my travels.

**Comment by cable729** [comment]
@tlil87 - How will this this affect the [conventions](https://github.com/graphql-dotnet/conventions) library?

**Comment by tlil87** [comment]
@cable729 It will have minimal effect on the Conventions library as the graph type construction is abstracted away from the underlying way that the graphql-dotnet library currently constructs types. If anything, it will simplify the library down the line :) I hope to have a preliminary release of Conventions ready early this upcoming week, so will let you know when it's out.

**Comment by cable729** [comment]
Awesome, is there anything I can do to help?

**Comment by tlil87** [comment]
@cable729 Thanks for asking - let's touch base when the first release is out and we can talk about next steps. Sound like a plan?

**Comment by joemcbride** [comment]
Closing this for now.

**Comment by SimonCropp** [comment]
@joemcbride time to delete this branch?

**Pull request closed without merging**
