### PR TITLE
make GraphTypeTypeRegistry thread safe

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by sungam3r** [comment]
Are you really faced with thread safety issues? Or is this a change for the future?

**Comment by SimonCropp** [comment]
yeah i had it happen a few times. i have different tests running in parallel that can add diff types to GraphTypeTypeRegistry.

**Comment by sungam3r** [comment]
LGTM. This change will really fix this error, but keep in mind that the whole schema is not thread safe. It is not designed for thread safety.

**Comment by SimonCropp** [comment]
the schema i can instantiate in each test (or group of tests) so that ok

**Comment by sungam3r** [comment]
Also since `GraphTypeTypeRegistry` is a static type all its methods should be thread safe by design. It was an initial mistake not to use a thread safe dictionary.

**Pull request merged**
