### PR TITLE
DecimalGraphType parsing fixed when thread culture decimal point is ','

### PR DESCRIPTION
**Pull request by mule**
Fix for issue #302  (which was closed for some reason).

### CODE REVIEW

**Comment by joemcbride** [comment]
@mule  Thanks for the PR! #302 was not closed ... there was a duplicate report that was closed though.  Can you please add tests that run this code under a non-US culture to verify this behavior?

**Comment by schlaup** [comment]
@mule Thanks for working on this! I've never gotten to it. In your commit "Improved conversion, decimal to decimal conversion now works for different cultures" you allow parsing of the current server's culture. I believe this is too much magic. For example, someone might accidently input a number with thousand-separator. (US: 11,000) If your implementation runs on a DE server it would convert this to "11.000" and allow the value. I believe, it should always throw an error. The GraphQL API should always use invariant culture and should not allow other formats if it runs on a server with a different locale setting.

**Comment by pekkah** [comment]
Is this being worked on? Hitting this issue while running unit tests.

**Comment by pekkah** [comment]
This can be closed now?

**Comment by joemcbride** [comment]
Yes, this PR was superseded by #434

**Pull request closed without merging**
