### PR TITLE
feat: support user-defined Edge and Connection types

### PR DESCRIPTION
**Pull request by benmccallum**
Adds support for user-defined Edge and Connection types so custom properties can be added to them as needed.

Addresses #1093 
Builds on #1066

### CODE REVIEW

**Comment by benmccallum** [comment]
FYI, there's a commit in there from @SimonCropp which I'm not sure is about, I just saw it in an active branch and didn't want to be working on stuff in the same place if he had WIP. 

With/without his changes we can make this work.

Includes unit tests, will probably need to update docs too. I'll hold off on that until you give this a review and thumbs up @joemcbride

**Comment by benmccallum** [comment]
I've got one test failing and I'm not sure why. Will take a look.

**Comment by benmccallum** [comment]
Fixed. Over to you @SimonCropp fo rreview!

**Comment by benmccallum** [comment]
Something I noticed yesterday is that the `ConnectionBuilder` doesn't provide any type checking for the resolver. It just requires a response of `object`. Could we add overloads for one that is? I'd like that extra sense of security.

**Comment by jwx** [comment]
Is there an ETA for this?

**Comment by benmccallum** [comment]
@SimonCropp has approved it so I guess if @joemcbride can merge it'd then be a matter of falling into the next release whenever that is.

**Comment by benmccallum** [comment]
Sorry guys I made this a little confusing by targeting @SimonCropp's branch. Will create another that targets master.

**Pull request merged**
