### PR TITLE
Enforce formatting in Visual Studio rather than by dotnet-format

### PR DESCRIPTION
**Pull request by Shane32**
This should work much better.  No need to push bad code just to have CI tests flunk it.

### CODE REVIEW

**Comment by sungam3r** [comment]
Please try push some file with unnessessary usings and check if CI fails this commit.

**Comment by Shane32** [comment]
It doesn’t, and nor is it designed to.   Nor would I have it do so.

**Comment by Shane32** [comment]
I specifically tested it to be sure it wouldn’t.

**Comment by sungam3r** [comment]
I specifically added dotnet-format to CI so that no one could merge the code that does not correspond to the defined rules. If you remove this check, then there is no protection from the fact that anyone can merge arbitrary code violating rules from any IDE (or even without any IDE). And then you or I have to correct this code yourself. Why? I don't want to bother with all that stuff.

**Comment by sungam3r** [comment]
> No need to push bad code just to have CI tests flunk it.

You solve this issue in the wrong way. The right decision will be to add rules in editorconfig to make issues (whitespaces or something else) explicitly visible in IDE.

**Comment by sungam3r** [comment]
> dotnet_diagnostic.IDE0005.severity = error

👍 Good, but it is not necessary to turn off dotnet-format.

**Comment by Shane32** [comment]
> The right decision will be to add rules in editorconfig to make issues (whitespaces or something else) explicitly visible in IDE.

Huh? That is what this does.

> > dotnet_diagnostic.IDE0005.severity = error
>
> 👍 Good, but it is not necessary to turn off dotnet-format.

Well, it is if we want to use a source-only repo.

**Comment by Shane32** [comment]
> I specifically added dotnet-format to CI so that no one could merge the code that does not correspond to the defined rules. If you remove this check, then there is no protection from the fact that anyone can merge arbitrary code violating rules from any IDE (or even without any IDE).

Yes, I know.  I know this is personal opinion, but I do not like the formatter.  I find it extremely annoying that it constantly rejects code changes because of a BOM or extra using or spacing that it isn't happy with.  So I often have to spend an extra 5-10 minutes waiting for code to be pushed tested and rejected, and I don't have that kind of time to waste.  I would much rather 'encourage' proper formatting than 'enforce' proper formatting.  I would much rather that the editor suggest changes, rather than having no idea that the code will be rejected until CI tests execute.  But I don't mind the formatter so terribly much if it's important to you.

Now in this case, you suggested that we use a source-only repo for nullability detection.  I am trying to suggest a way in which we can do so.  You suggested the exclude parameter; that didn't work.  This was another suggestion.

**Comment by sungam3r** [comment]
You can setup dotnet-format to run locally if editorconfig does not work for your cases. Either as additional build step (conditional) or external command invoked by hotkey.

>  I would much rather 'encourage' proper formatting than 'enforce' proper formatting.

I would also do that, if in practice it was. Experience shows that it is not.

**Comment by sungam3r** [comment]
> You suggested the exclude parameter; that didn't work.

I'll try myself.

**Comment by sungam3r** [comment]
See #2890

Red: https://github.com/graphql-dotnet/graphql-dotnet/runs/4985533002?check_suite_focus=true
Green: https://github.com/graphql-dotnet/graphql-dotnet/runs/4985633359?check_suite_focus=true

Fixed in https://github.com/graphql-dotnet/graphql-dotnet/pull/2890/commits/548237e8fbb4c462fed94f4ed07fd4278e415113

**Pull request closed without merging**
