### PR TITLE
Merge NotAGraphTypeAnalyzer to develop branch

### PR DESCRIPTION
**Pull request by gao-artur**
Merging master to develop with a PR because there were many conflicts, and I wanted another pair of eyes to verify I didn't miss something.

### CODE REVIEW

**Comment by Shane32** [comment]
Well, we don't squash-merge master to develop so that the PRs (commits) to master are seen in develop.  So we can't actually merge this via a PR.  I usually merge master to develop as necessary by hand, so let me check it out.

**Comment by Shane32** [comment]
Or i can temporarily enable merge commit

**Comment by gao-artur** [comment]
Oh... I have seen a couple of merge commits in the develop branch and thought this was the way. I already did one before...

**Comment by Shane32** [comment]
No problem.  We will merge this and then all the commits to master will be seen in develop, including any missed by previous PR-merges.

**Review by Shane32 — APPROVED** [review]

**Comment by gao-artur** [comment]
Thanks!

**Comment by Shane32** [comment]
So the goal is the develop branch to look like this:

image

So we can see the PRs made to master, and the PRs made to develop, and the point at which it was merged.

I usually just title the merge commit "merge from master" or similar, as it won't have an associated PR (assuming it's done from VS, and not via PR).

**Comment by Shane32** [comment]
So you can see all my merge commits there such as "Merge branch 'master' into develop" (usually auto labeled by VS), and at any point in time we can fork from a commit to diagnose an issue.

**Comment by gao-artur** [comment]
Got it!

**Comment by Shane32** [comment]
FYI go ahead and do the same as necessary.  And FYI, usually if I expect to merge a PR to master that will cause a bunch of merge conflicts, well, first I ensure that develop is merged before I begin, and then I immediately after the PR is merged, I merge master to develop again, so that other devs (or myself) won't wonder what to do with the merge conflicts.

**Comment by Shane32** [comment]
I've also been wanting to change all the files in the repo to file-scoped namespaces.  But that kind of change will cause immense merge conflicts as we continue to push changes to v7/master.  So I've been holding out until v8 is released (or immediately prior to its release) to do that kind of thing.

**Comment by Shane32** [comment]
Oh one more comment, I'm not terribly concerned about tests not running in CI when manually merging master to develop.  I run tests locally before merging a merge commit, and if I forget, then next PR to develop will show build errors or test failures which will require a PR to fix.

**Comment by gao-artur** [comment]
Do you have ETA for v8 release?

**Comment by gao-artur** [comment]
@Shane32 did you make the develop branch protected? I can't push the merge from master

> Remote: Error: GH006: Protected branch update failed for refs/heads/develop.        
> Remote: Error: Required status check "buildcheck" is expected.        
> To https://github.com/graphql-dotnet/graphql-dotnet.git
> Error:   develop -> develop (protected branch hook declined)
> failed to push some refs to 'https://github.com/graphql-dotnet/graphql-dotnet.git'
> 
> Error encountered while pushing to the remote repository: Failed to push to the remote repository. See the Output window for more details.
> Failed to push to the remote repository. See the Output window for more details.

**Comment by Shane32** [comment]
Hmm; I have not made any changes recently…

**Comment by Shane32** [comment]
Try this: delete your local develop branch, then pull it and try merging from master again.

**Comment by gao-artur** [comment]
I fully removed the repo and cloned it again, but I still can't push the merge
image

**Comment by Shane32** [comment]
Huh. Well technically I’m an admin for the repo so maybe that’s why.

**Comment by Shane32** [comment]
Maybe if you create a PR but push it by hand after status checks pass it will work? (Rather than using squash and merge button)

**Comment by gao-artur** [comment]
But I was able to push a month ago...
image

Anyway, I'll try with a PR.

**Comment by Shane32** [comment]
I can disable “status checks are required” if it’s a problem. Don’t know why it would have changed.

**Pull request merged**
