### PR TITLE
New Parser

### PR DESCRIPTION
**Pull request by joemcbride**
Once completed this will allow the removal of Antlr and make supporting .NET Core easier.

#2 #43

### CODE REVIEW

**Comment by tlil87** [comment]
Like it – I was planning on having a stab at this myself after the Conventions work.

**Comment by joemcbride** [comment]
Down to 20 failing tests.

**Comment by joemcbride** [comment]
All tests passing with the new parser!  🎉

**Comment by tlil87** [comment]
Nice! 👍 🎉 Excited!

**Comment by joemcbride** [comment]
Unfortunately, there is quite the perf difference parsing the following query.  Thoughts?

```
query SomeDroids {
   r2d2: droid(id: ""3"") {
     ...DroidFragment
   }

   c3po: droid(id: ""4"") {
     ...DroidFragment
   }
}
fragment DroidFragment on Droid {
  name
}
```

Parse times:
```
(100) AntlrDocumentBuilder Time elapsed: 00:00:00.1060146
(1000) AntlrDocumentBuilder Time elapsed: 00:00:00.0719086
(10000) AntlrDocumentBuilder Time elapsed: 00:00:00.7042157

(100) SpracheDocumentBuilder Time elapsed: 00:00:00.2949347
(1000) SpracheDocumentBuilder Time elapsed: 00:00:01.6270808
(10000) SpracheDocumentBuilder Time elapsed: 00:00:16.5569542
```

**Comment by joemcbride** [comment]
Doing some research last night, [this new GraphQL project](https://github.com/mkmarek/graphql-dotnetcore/tree/master/src/GraphQLCore/Language) has its own parser/lexer in C#.  I don't know if its fully implemented, though it looks like it may be.  Comparable perf to Antlr, even faster.  That is running on dotnet core, so perf could be a little different on the full .NET framework.  License for that project is MIT, so hopefully he won't mind if we use it.

```
(100) Time elapsed: 00:00:00.0044104
(1000) Time elapsed: 00:00:00.0496866
(10000) Time elapsed: 00:00:00.4506858
```

**Comment by joemcbride** [comment]
Comparison after @randyridge changes.

```diff
(100) AntlrDocumentBuilder Time elapsed: 00:00:00.1108924
(1000) AntlrDocumentBuilder Time elapsed: 00:00:00.0848008
(10000) AntlrDocumentBuilder Time elapsed: 00:00:00.7402738

-(100) SpracheDocumentBuilder Time elapsed: 00:00:00.2949347
-(1000) SpracheDocumentBuilder Time elapsed: 00:00:01.6270808
-(10000) SpracheDocumentBuilder Time elapsed: 00:00:16.5569542
+(100) SpracheDocumentBuilder Time elapsed: 00:00:00.2610134
+(1000) SpracheDocumentBuilder Time elapsed: 00:00:00.9174769
+(10000) SpracheDocumentBuilder Time elapsed: 00:00:09.0484814
```

**Comment by joemcbride** [comment]
> Did you try to benchmark that parser explicitly with this use case?

I used the same query if that is what you mean, and it appeared it was fully populated.

**Comment by tlil87** [comment]
@joemcbride 👍 Sounds good – and performance-wise in those tests you said it was on par / faster than the Antlr, right?

**Comment by joemcbride** [comment]
I've brought in the code from the other project and it does run crazy fast.  I wrote a converter its AST to our AST to track down issues.  The parser/lexer suffers from similar issues that we once had, this is what I've found so far:

* Line numbers are not being tracked directly but are expected to be calculated later, this can be slow and requires the original string to calculate
* Groups of types such as arguments/directives/object values are not tracking location, so you cannot accurately report location in errors (when compared to the JS project)
* using `float` instead of `double`
* does not support `long` numbers

Currently 73 tests failing, mostly around validation, due to the line/column issue.

```
// this includes converting between ASTs
(1) GraphQLDocumentBuilder Time elapsed: 00:00:00.0648309
(10) GraphQLDocumentBuilder Time elapsed: 00:00:00.0008090
(100) GraphQLDocumentBuilder Time elapsed: 00:00:00.0054521
(1000) GraphQLDocumentBuilder Time elapsed: 00:00:00.0516097
(10000) GraphQLDocumentBuilder Time elapsed: 00:00:00.5676733
```

I've reached out to the own of that project to see if he would be interested in a shared nuget that is just the lexer/parser.  So each of our projects could use it and we would have a centralized place to fix bugs and add features.

**Comment by tlil87** [comment]
Nice - yep that makes sense :+1:

**Comment by joemcbride** [comment]
Little bit of elbow grease and I got all the tests passing.  The build needs to be updated and the nuget will be broken, though happy to have a super fast parser.

**Comment by tlil87** [comment]
Yay!! That's great!

**Comment by randyridge** [comment]
fyi, i ported the graphql-js *lexer* and it appears to be 7x faster than the dotnetcore one, not sure how much overall benefit that would give and i haven't diffed the performance between the two, maybe i'll get to it this weekend

**Comment by joemcbride** [comment]
Nice - would be good to look at. We pulled the parser/lexer into its own Nuget and project.

http://github.com/graphql-dotnet/parser

**Comment by randyridge** [comment]
on my machine with 1MM of your showdown tests in release mode:
core_builder: (1000000) GraphQLDocumentBuilder Time elapsed: 00:00:34.9865384
new_lexer: (1000000) GraphQLDocumentBuilder2 Time elapsed: 00:00:10.3672227

I think I have a bit more room for perf enhancements.  I'll try to get a repo with it before the weekend is out, but we'll see...

also I suggest taking a look at BenchmarkDotNet for these types of things

**Comment by wesamco** [comment]
Hey Great job @joemcbride. I can't wait for .Net core support. 
but why create a specific parser? bech prefs seems better with ANTLR, it seems ANTLR 4 is being ported to .net core soon, see [#antlr4/1114](https://github.com/antlr/antlr4/issues/1142) & entity framework core members seems interested in it.

**Comment by joemcbride** [comment]
@wesamco re C++ - that would be a good idea, though I'm not a C++ dev myself.  I had the same suggestion about a year ago (to the day)  https://github.com/graphql-dotnet/graphql-dotnet/issues/2#issuecomment-134047350 with no takers yet.  My last [foray into C/C++ wrappers](https://github.com/joemcbride/react-native-wpf) created scary code.

Having it be in C# includes more opportunity for contributors, though I'll still be open to targeting the C++ wrapper if someone makes one.

**Comment by dNetGuru** [comment]
I can look into the C++ route for you.
Mind you that having native assemblies will make it platform/arch dependent and would require distribution of the compiled native assemblies with the packages.

Using protocol buffers might look attractive in this case as well.

Can you clarify if you are waiting for Antlr's port to .Net Core or if you are thinking about getting rid of Antlr?

**Comment by joemcbride** [comment]
@dNetGuru Using this new parser or the C++ one would mean not using Antlr.  Antlr is a generic language parser/lexer framework.

Looking at the C++ project again, it looks like it excludes parsing Schema definitions (and won't ever include it according to the author), which this new parser includes.  I'm not doing anything with that right now, though that has me leaning towards this one because of that.

**Comment by dNetGuru** [comment]
Today I had some free time and got the parser to compile on win32 with minor edits to the source/headers and it works perfectly.

However after I tried integrating the resulting library into a CoreCLR project I ended up facing a lot of problems and some digging led me to https://github.com/dotnet/coreclr/issues/641 and https://github.com/dotnet/coreclr/issues/659. I guess if the objective is to support .Net Core then this approach is not going to work.

Let me know if you want to take a look at the parser compiled for win32.

**Comment by joemcbride** [comment]
@dNetGuru Thanks for taking a stab at it!  I think it would be nice to have a repo up for it.  I would be interested to see it working.  If nothing else it can be revisited once c/cli is supported in .NET Core.  For now sounds like we stick to the C# parser.

**Comment by wesamco** [comment]
@dNetGuru  Cool. push it to a repo.
I remmemer I saw in KestrellHttpServer uses Libuv, with some Intreop. Libuv is written in C and C++
in the KestrellHttpServer project.json in dependenies there is "Libuv": "1.9.0", I think this is for the Native platform specific binaries of Libuv that they reference in the dllimports in
https://github.com/aspnet/KestrelHttpServer/blob/08d7f661084cabf8b95520f917c00de88bf57d40/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs#L494

**Pull request merged**
