### PR TITLE
make ServiceProviderExtensions internal

### PR DESCRIPTION
**Pull request by SimonCropp**
The majority of things consuming will already reference `Microsoft.Extensions.DependencyInjection.Abstractions`. Which means ServiceProviderExtensions regularly causes type conflicts when using as an extension method

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 
'GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService<T>(System.IServiceProvider)' and 
'Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(System.IServiceProvider)'	
```

So this PR makes ServiceProviderExtensions internal

### CODE REVIEW

**Review by Shane32 — APPROVED** [review]

**Comment by sungam3r** [comment]
Yes, it's really obvious, I've come across this myself.

**Comment by sungam3r** [comment]
But formally it is still a breaking change.

**Comment by sungam3r** [comment]
I propose to target this PR to `develop` branch and add note to https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/docs2/site/docs/guides/migration4.md

**Review by joemcbride — APPROVED** [review]

**Comment by Shane32** [comment]
I agree - let’s prevent breaking changes in 3.x releases

**Comment by SimonCropp** [comment]
replaced by https://github.com/graphql-dotnet/graphql-dotnet/pull/1931 and upgrade guide note added

**Pull request closed without merging**
