### PR TITLE
Fix to SchemaTypes.RebuildType

### LINKED ISSUE #2415: Can't resolve generic types that use GraphQL clr reference types
My schema builder constructed the following graph type:
- `ConnectionType<GraphQLClrOutputTypeReference<Widget>>`

(Note: `ConnectionType<>` is provided with GraphQL.)

However, during schema initialization, the "wrapped" reference type was not resolved, since it was not recognized as a GraphQL reference type.

This breaks my use case.  I will provide a fix within the library as a PR in which it will examining each generic graph type to determine if it needs to be reconstructed.  I will also (eventually) provide a PR to `SchemaTypes` that has enough protected members to allow overriding portions of it as necessary to fix unforeseen problems like this in the future.

### PR DESCRIPTION
**Pull request by Shane32**
Fixes #2415 

@sungam3r I would like to merge this asap.

### CODE REVIEW

**Review by sungam3r — APPROVED** [review]
Good fix. I did not think of this obvious thing when I wrote this method. One suggestion. At the beginning of `RebuildType` I would like to add additional check like this
```csharp
if (type.IsGenericTypeDefinition)
  throw new InvalidOperationException($"GraphType {type} should not be an open generic type definition");
```

To test this change `test` field to
```csharp
 var field = query.Field(typeof(ConnectionType<>), "test");
```

Or even change `FieldType.Type.set` to throw if `value` is generic type definition.

**Comment by sungam3r** [comment]
And remember to bump VersionPrefix to 4.0.2

**Comment by Shane32** [comment]
I won't release 4.0.2 just yet

**Comment by sungam3r** [comment]
OK

**Comment by Shane32** [comment]
@sungam3r I ran into an issue in my code where an enumeration type is not resolved by the type mapper.  I need a little more time to investigate.  It may be related to this bug here, .... still checking.  It's also likely enough that I need to fix something else in my own code.

**Pull request merged**
