### PR TITLE
Add deserialize-variables stage to benchmarks

### PR DESCRIPTION
**Pull request by Shane32**
Adds stage: DeserializeVars

```
|        Method |           Stage |             Mean |          Error |         StdDev |    Gen 0 |    Gen 1 | Gen 2 | Allocated |
|-------------- |---------------- |-----------------:|---------------:|---------------:|---------:|---------:|------:|----------:|
| Introspection |           Build | 5,433,452.031 ns | 18,541.4741 ns | 17,343.7064 ns | 414.0625 | 132.8125 |     - | 2626413 B |
| Introspection |           Parse |    17,797.519 ns |    164.6261 ns |    153.9913 ns |   1.8921 |   0.0610 |     - |   11920 B |
| Introspection |         Convert |     9,463.905 ns |     43.2809 ns |     40.4850 ns |   2.6550 |   0.1373 |     - |   16696 B |
| Introspection |        Validate |   179,113.175 ns |    636.5009 ns |    595.3833 ns |   1.7090 |        - |     - |   11616 B |
| Introspection | DeserializeVars |         1.298 ns |      0.0069 ns |      0.0065 ns |        - |        - |     - |         - |
| Introspection |  ParseVariables |         2.967 ns |      0.0181 ns |      0.0170 ns |        - |        - |     - |         - |
| Introspection |         Execute |   661,182.269 ns |  3,289.6879 ns |  3,077.1761 ns |  52.7344 |  17.5781 |     - |  335846 B |
| Introspection |       Serialize |   112,221.930 ns |    308.1840 ns |    273.1971 ns |   4.3945 |   0.3662 |     - |   27920 B |
|               |                 |                  |                |                |          |          |       |           |
|          Hero |           Build | 5,482,710.469 ns | 19,253.5183 ns | 18,009.7530 ns | 414.0625 | 132.8125 |     - | 2626365 B |
|          Hero |           Parse |       809.267 ns |      2.8122 ns |      2.6305 ns |   0.1249 |        - |     - |     784 B |
|          Hero |         Convert |       505.542 ns |      1.5950 ns |      1.4919 ns |   0.1831 |        - |     - |    1152 B |
|          Hero |        Validate |    10,944.340 ns |     36.4785 ns |     30.4612 ns |   0.4730 |        - |     - |    2976 B |
|          Hero | DeserializeVars |         1.322 ns |      0.0079 ns |      0.0066 ns |        - |        - |     - |         - |
|          Hero |  ParseVariables |         2.414 ns |      0.0098 ns |      0.0091 ns |        - |        - |     - |         - |
|          Hero |         Execute |     2,082.783 ns |      8.1636 ns |      6.8170 ns |   0.3891 |        - |     - |    2464 B |
|          Hero |       Serialize |       534.068 ns |      2.1121 ns |      1.9756 ns |   0.0858 |        - |     - |     544 B |
|               |                 |                  |                |                |          |          |       |           |
|     Variables |           Build | 5,081,011.886 ns | 14,181.7008 ns | 12,571.7083 ns | 398.4375 | 101.5625 |     - | 2517769 B |
|     Variables |           Parse |     1,554.299 ns |      3.6229 ns |      3.3889 ns |   0.1602 |        - |     - |    1008 B |
|     Variables |         Convert |       632.114 ns |      1.7229 ns |      1.5273 ns |   0.2365 |   0.0010 |     - |    1488 B |
|     Variables |        Validate |    19,891.310 ns |     89.5117 ns |     74.7463 ns |   1.5564 |        - |     - |    9865 B |
|     Variables | DeserializeVars |     9,458.814 ns |     28.4030 ns |     25.1785 ns |   1.3123 |   0.0305 |     - |    8288 B |
|     Variables |  ParseVariables |    32,806.175 ns |    147.9092 ns |    138.3544 ns |   2.3193 |        - |     - |   14879 B |
|     Variables |         Execute |     2,811.702 ns |     10.6793 ns |      9.9895 ns |   0.3510 |        - |     - |    2224 B |
|     Variables |       Serialize |       376.860 ns |      1.0728 ns |      1.0035 ns |   0.0863 |        - |     - |     544 B |
|               |                 |                  |                |                |          |          |       |           |
|       Literal |           Build | 5,119,479.167 ns | 25,909.0337 ns | 24,235.3262 ns | 398.4375 | 101.5625 |     - | 2517766 B |
|       Literal |           Parse |    18,696.642 ns |     68.4530 ns |     64.0310 ns |   1.4343 |   0.0305 |     - |    9016 B |
|       Literal |         Convert |     7,805.960 ns |     30.6605 ns |     28.6798 ns |   2.0447 |   0.0610 |     - |   12888 B |
|       Literal |        Validate |   134,817.244 ns |    346.8342 ns |    324.4289 ns |   4.3945 |        - |     - |   27712 B |
|       Literal | DeserializeVars |         1.325 ns |      0.0039 ns |      0.0033 ns |        - |        - |     - |         - |
|       Literal |  ParseVariables |         2.417 ns |      0.0070 ns |      0.0062 ns |        - |        - |     - |         - |
|       Literal |         Execute |    31,638.282 ns |    221.9045 ns |    207.5696 ns |   2.2583 |        - |     - |   14504 B |
|       Literal |       Serialize |       391.332 ns |      1.0904 ns |      1.0199 ns |   0.0863 |        - |     - |     544 B |
```

### CODE REVIEW

**Comment by sungam3r** [comment]
I suggest to remove Error and StdDev columns. This will help a lot. I'm tired of using scrolling.

**Comment by Shane32** [comment]
It's now evident (although we knew this before) how much more time and memory it takes to process literals versus variables, even considering the time and memory required to deserialize the variables.

**Comment by Shane32** [comment]
> I suggest to remove Error and StdDev columns. This will help a lot. I'm tired of using scrolling.

I agree, but don't know how.

**Comment by Shane32** [comment]
Go ahead and push the required change if you know how.

**Comment by Shane32** [comment]
Ideally we could reduce the amount of precision shown in these numbers and/or skip tests for the phases that are not applicable.  I think that the no-op stages produce such low values that it forces the results to show more decimal places.

**Review by sungam3r — APPROVED** [review]

**Pull request merged**
