### PR TITLE
Added support for null input argument

### PR DESCRIPTION
**Pull request by HasAndries**
This will handle the new null input argument that will come from the parser change in this PR: https://github.com/graphql-dotnet/parser/pull/10
The issue for this change is https://github.com/graphql-dotnet/parser/issues/9

### CODE REVIEW

**Comment by HasAndries** [comment]
The build seems to be broken. Is this something that you are aware of?

**Comment by joemcbride** [comment]
Yes, AppVeyor updated to VS2017 csproj and we're still on project.json.   This can potentially be fixed by adding a global.json until the project is updated to the new csproj format.  See #311

**Comment by joemcbride** [comment]
Added the sdk to the `global.json` file, so if you rebase on master that should be fixed.

**Comment by HasAndries** [comment]
@joemcbride Thanks for the fix, the build is passing. Any chance we can add this change sometime soon?

**Comment by joemcbride** [comment]
Sorry for the delay on this, though I'm concerned that there would be more places that we would need to handle null, which is why it has lingered so long.  Have you looked at the JavaScript implementation to check its usage?

**Comment by joemcbride** [comment]
Closing in favor of #374

**Pull request closed without merging**
