### PR TITLE
Add typed IDocumentExecuter (#3016)

### PR DESCRIPTION
**Pull request by Shane32**
Cherry pick of #3016 targeting the `master` branch.

### CODE REVIEW

**Review by sungam3r — APPROVED** [review]
Need to fix migration5?

**Comment by Shane32** [comment]
> Need to fix migration5?

I would not.  This is still essentially a new feature for v5.  It is questionable if we will release 4.8 before v5 anyway; most likely we will release them simultaneously.

**Comment by Shane32** [comment]
As you have approved, I will merge this PR manually so git will understand the cherry-pick properly.  (I hope)

**Comment by Shane32** [comment]
Well, it didn't help, but that's okay.  It is all merged properly.

**Pull request merged**
