### PR TITLE
Enable ExecutionOptions.Indent

### PR DESCRIPTION
**Pull request by deinok**

### CODE REVIEW

**Comment by joemcbride** [comment]
These extension methods are to help get you started.  Since that indent is not related to the execution I don’t want it on that class.  I would be fine with an optional parameter in the extension method.

**Comment by deinok** [comment]
@joemcbride Is there a more performant way?

**Comment by joemcbride** [comment]
@deinok Its less about performance and more about design.  The `ExecutionOptions` go with the `DocumentExecuter` class.  I don't want to add a property related to the `DocumentWriter` to the class that is paired with the `DocumentExecuter`.

Something more like this would be acceptable:

```csharp
public static string Execute(
    this ISchema schema,
    Action<ExecutionOptions> configure,
    bool indent = true)
{
    ...
}

public static string Execute(
    this ISchema schema,
    Action<ExecutionOptions> configure,
    Action<WritingOptions> configureWrite = null)
{
    ...
}

public class WritingOptions
{
    public Formatting Formatting { get; set; } = Formatting.None;
    public JsonSerializerSettings SerializationSettings { get; set; } =
        new JsonSerializerSettings
        {
            DateFormatHandling = DateFormatHandling.IsoDateFormat,
            DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFF'Z'",
        };
}
```

**Comment by deinok** [comment]
Are PRs for this accepted?

**Comment by joemcbride** [comment]
Yep

**Pull request closed without merging**
