### PR TITLE
add test + document behaviour for null field comparers preserving ori…

### PR DESCRIPTION
**Pull request by adamjones1**
…ginal ordering

### CODE REVIEW

**Comment by Shane32** [comment]
See PR #1907

**Comment by Shane32** [comment]
@sungam3r Can we merge this into PR #1907 ?

**Comment by sungam3r** [comment]
I need to look first. It will take no more than a few hours.

**Comment by sungam3r** [comment]
I changed default behavior in #1907

**Comment by sungam3r** [comment]
@adamjones1 Thanks for PR. Your test helped. I copied it to #1907 and changed it as needed because I changed the default behavior in #1907.

**Pull request closed without merging**
