### PR TITLE
Simplify resolver interfaces and context

### PR DESCRIPTION
**Pull request by pekkah**
* AsyncResolver (No more returning Task<T> with null value)
* Make more sense with the inheritance chain of the ResolverFieldContext

### CODE REVIEW

**Comment by joemcbride** [comment]
I'll take a closer look next week, though my initial response is I'm not sure I'm comfortable with these changes.  If nothing else, due to the hard break in compatibility (this could have a very large impact).

Do you have a specific use case you are trying to solve?

**Comment by pekkah** [comment]
I'm trying to simplify interfaces and the context for resolving fields so I can actually add to them features related to two other issues I opened earlier. Now the resolving just has too much magic related to the type of the source object, using new keyword in the interfaces, weird inheritance chain in the context that any changes to them causes too many complications.

**Comment by joemcbride** [comment]
Still feeling uncomfortable with these changes.  Mainly with the `Source` -> `SourceObject` change and the addition of the async resolver.  I think I would prefer to break people and make returning `Task` required vs. having two different resolvers that the library has to guess which one to use.

**Comment by pekkah** [comment]
Ok no problem. I'll see if I can clean it up without breaking anything.

**Comment by BenjaBobs** [comment]
This pr was closed a long time ago, but I think it has some good ideas that should be considered again. In particular, a less complex inheritance chain.
Something like:
```c#
public class ResolveFieldContext
{
	//...
	public object Source { get; set; }
}

public class ResolveFieldContext<TSource> : ResolveFieldContext
{
	public new TSource Source { get => (TSource)base.Source; set => base.Source = value; }
}
```

This would increase flexibility in cases where the exact type isn't known / necessary.

**Comment by pekkah** [comment]
#1440

**Comment by pekkah** [comment]
#658

**Comment by pekkah** [comment]
#1437

**Comment by sungam3r** [comment]
@pekkah Do you mind deleting a branch?

**Pull request closed without merging**
