### PR TITLE
Allow GetArgument with default value to operate on reference types

### LINKED ISSUE #2557: Why the `IsValueType` check?
When using `context.GetArgument<TType>(name, defaultValue)` with non-value types (such as `List<string>`), the default value is ignored. Why is this check there? Is it needed for anything? 

https://github.com/graphql-dotnet/graphql-dotnet/blob/3c6749f5cc2dd87735ce27571f0765b8501b6d03/src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs#L28

### PR DESCRIPTION
**Pull request by Shane32**
Fixes #2557 

The bug is a regression against v3.2.0 and prior, but exists in 3.3.0 and newer.  The bug was introduced in ~#1456~ #2160.

### CODE REVIEW

**Comment by sungam3r** [comment]
I think that this "bug" was not introduced in #1456. 

Look at `exists` flag.
изображение

Before changes in `ExecutionHelper.GetArgumentValues` and introduction of `ArgumentValue` this `exists` flag works well. Now it is always `true` (@Shane32 I think you can check it easily) so execution **always** flows to the first branch, not just returning `defaultValue`. I already do not remember exactly the progress of my thoughts, but this check was completely added to properly process defaults for ref types.

**Comment by Shane32** [comment]
> I think that this "bug" was not introduced in #1456.

You're right; I did a whole bunch of before/after testing and traced it to #2160 .  After #2160 breaks many of the tests in this PR that passed before.  #2160 was included with version 3.3.0 so this bug has existed since then but not before.

Is there any reason not to merge this PR?  The new tests exercise as many combinations of default values as I can think of, and everything works properly now.

**Comment by Shane32** [comment]
@sungam3r if you have no further comments, I’ll merge this.

**Comment by sungam3r** [comment]
Just reviewed. Well, I don't remember all our refactorings around arguments and default values, I just hope that huge testing eventually allows to achive the right behavior.

**Pull request merged**
