### PR TITLE
Tweaks for NugetPackageExplorer green badges

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Review by Shane32 — APPROVED** [review]
`PackageProjectUrl` isn't necessary?

**Comment by sungam3r** [comment]
Yes, `PublishRepositoryUrl` make the trick.

**Comment by sungam3r** [comment]
I can make 3.1.3 release to demonstrate this and better SourceLink support.

**Comment by sungam3r** [comment]
3.1.3-preview
изображение


3.1.2-preview
изображение

**Comment by Shane32** [comment]
Nice! 👍

**Pull request merged**
