### PR TITLE
Make types in GraphTypesLookup non static

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Review by Shane32 — APPROVED** [review]

**Comment by sungam3r** [comment]
Because of this, someone may have serious problems with the previous release.

**Comment by sungam3r** [comment]
I think it is time to release 3.1.1 with this bugfix.

**Comment by Shane32** [comment]
Ok want me to do so?  Or you can.

**Comment by Shane32** [comment]
You already did 👍

**Comment by sungam3r** [comment]
Will we continue to name each release simply as 'Version X.Y.Z'?

изображение

Also will we drop published nugets into each release (3 nupkgs)?

**Comment by sungam3r** [comment]
I updated 3.1.0 release with 3 packages. No action triggered. Good.

**Comment by Shane32** [comment]
> Will we continue to name each release simply as 'Version X.Y.Z'?

Seems fine to me.

**Comment by Shane32** [comment]
Note: bug introduced in #1887 / version 3.1.0

Fixed in version 3.1.1

**Pull request merged**
