### PR TITLE
Removed blocking of main thread. Passed CancellationToken into spawned threads

### PR DESCRIPTION
**Pull request by holm0563**
These fixes prevent thread starvation when processing a high number of graph queries that are running asynchronously. Will improve performance significantly under heavy load.

### CODE REVIEW

**Comment by holm0563** [comment]
This is failing on test: ThreadPerformanceTests.Executes_IsQuickerThanTotalTaskTime which was previously skipped. My guess is its machine specific and needs to processors to run correctly. Any suggestions? This was not changed as part of this pull request.

**Comment by joemcbride** [comment]
I have seen it fail intermittently on CI.  May just need to try to run it again, or bump of the time while on CI.

**Comment by joemcbride** [comment]
I kicked off a new build.

**Comment by joemcbride** [comment]
Ran this a couple more times, both being > 900 and < 1000.  So may be sufficient to bump it to 1k for now.  The ~1300 was probably an outlier.

**Comment by JonasZ95** [comment]
`await Task.WhenAll(externalTasks.ToArray());`

You can remove the ToArray() here aswell unless I'm wrong.

**Pull request merged**
