### PR TITLE
Delete UseRuntimeTypeMappings property

### PR DESCRIPTION
**Pull request by Shane32**
I'm not sure how this got set to false.  This should be fixed **_immediately_**.

### CODE REVIEW

**Comment by Shane32** [comment]
I must have had the impression that it would be set to true to "improve" performance.

**Comment by Shane32** [comment]
Also, I just did a full benchmark.  Setting the property to false/true has absolutely no effect on performance.

**Comment by Shane32** [comment]
The switch isn't mentioned anywhere in the migration documentation about `RegisterTypeMapping`.  It isn't mentioned in our documentation for custom scalars, which also mentions `RegisterTypeMapping`.  It isn't even listed along with the rest of the global switches in the migration document.

**Comment by Shane32** [comment]
Pretty sure we should be setting this back to `true`.  A number of the field builders won't work at all with it set to false.  The only "benefit" this property has is to discourage the use of expressions in field builders, which only indirectly makes a practical difference  for schemas with a scoped lifetime, which is already strongly discouraged throughout the document.  It would be more appropriate to mention with the documentation about scoped schema lifetime that setting this to false can help performance.  But if the user was concerned about performance, they probably wouldn't have a scoped schema lifetime to begin with.

**Comment by Shane32** [comment]
Note that the xml comment is wrong here as well.  It says "if you are using a scoped schema with many field expressions, then this setting will help speed up the initialization of your schema when set to false".  This is inaccurate.  It only helps speed up building the schema by the nature of preventing the use of field expressions.  It cannot speed up building the schema if you HAVE field expressions, as the slow part is compiling the expression, not converting a type reference.

**Comment by Shane32** [comment]
Finally, having the `[GraphQLMetadataAttribute]` attribute marked on a type does not allow an field builder via expression syntax to run any faster than using the type mappings, since it still needs to compile the expression.

**Comment by sungam3r** [comment]
When `UseRuntimeTypeMappings` is `true` then every _primitive_ type like `int`, `string`, `DateTime`, etc. is wrapped into `GraphQLClrOutputTypeReference<>`/`GraphQLClrInputTypeReference<>` and then rebuilded instead of directly returning graphtype from `SchemaTypes.BuiltInScalarMappings`.

**Comment by Shane32** [comment]
It is fortunate that this is not a breaking change.

**Comment by sungam3r** [comment]
> Also, I just did a full benchmark. Setting the property to false/true has absolutely no effect on performance.

It depends on your scenario.

**Comment by Shane32** [comment]
> > Also, I just did a full benchmark. Setting the property to false/true has absolutely no effect on performance.
> 
> It depends on your scenario.

No, it doesn't.  Give me any scenario.  It cannot improve performance.  All it can do is cause exceptions when attempting to use the field builder with expression syntax.

**Comment by Shane32** [comment]
> When `UseRuntimeTypeMappings` is `true` then every _primitive_ type like `int`, `string`, `DateTime`, etc. is wrapped into `GraphQLClrOutputTypeReference<>`/`GraphQLClrInputTypeReference<>` and then rebuilded instead of directly returning graphtype from `SchemaTypes.BuiltInScalarMappings`.

Ok I'll grant you that, but only if you're using an expression syntax.  And still it won't have any appreciable effect on build performance.  Compiling the expression syntax far outweighs any effect that above would have.

**Comment by sungam3r** [comment]
> as the slow part is compiling the expression, not converting a type reference.

Then let's do it simple - remove this property at all.

**Comment by sungam3r** [comment]
> Ok I'll grant you that, but only if you're using an expression syntax. And still it won't have any appreciable effect on build performance. Compiling the expression syntax far outweighs any effect that above would have.

OK, I'm OK to remove this property. No need in bump major version. Nobody uses this property yet.

**Review by sungam3r — APPROVED** [review]

**Pull request merged**
