### PR TITLE
Proposal: update target test FWs

### PR DESCRIPTION
**Pull request by SimonCropp**
IMO test suites should target the newest current release of supported runtimes. In this case that would be netcoreapp2.2 and net472. at the moment there is no consistency in the sln. eg `GraphQL.Tests.csproj` uses`netcoreapp2.1;netcoreapp2.0;netcoreapp1.1;net452`. ie 3 non-current netcore frameworks and one non-current desktop framework

### CODE REVIEW

**Comment by SimonCropp** [comment]
@joemcbride any guesses as the the test failure? it passes locally

**Comment by joemcbride** [comment]
Part of the idea is that the tests should run targeting the supported runtimes. Removing 1.1 and 452 in the tests could make it so regressions could creep in (though I do think 1.1 and 45x support should be removed in the next major released).  Do you not think that is the case?

**Comment by SimonCropp** [comment]
So only support net standard 2.0?

**Comment by SimonCropp** [comment]
replaced by https://github.com/graphql-dotnet/graphql-dotnet/pull/969

**Pull request closed without merging**
