### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by kamil-mrzyglod**
Updated Readme file with a full example, fixed method names and usings, so there is no need to seek them inside a solution.

### CODE REVIEW

**Comment by joemcbride** [comment]
I want to keep the example in the README super small.  I don't think all of this is needed on the front page.  I'm okay with adding the usings, though I don't want to add more classes.

**Comment by kamil-mrzyglod** [comment]
@joemcbride Sure, that's perfectly fine. From my point of view(someone who just tried to make example working) it was all a bit cumbersome - the example itself doesn't work so there is a need to dig into code to get it working.

Maybe adding usings and a link to `GraphQL.StarWars` project would make a deal?

**Comment by joemcbride** [comment]
I think it can be updated so that you can just copy-paste the code and have it work.  So having a `Droid` class and removing the `StartWarsData` references.

**Comment by kamil-mrzyglod** [comment]
@joemcbride Reverted and added only a link to the `StarWars` project.

**Comment by joemcbride** [comment]
```
namespace ConsoleApplication
{
    using System;
    using System.Threading.Tasks;
    using GraphQL;
    using GraphQL.Http;
    using GraphQL.Types;

    public class Program
    {
        public static void Main(string[] args)
        {
          Run();
        }

        private async static void Run()
        {
          Console.WriteLine("Hello GraphQL!");

          var schema = new Schema { Query = new StarWarsQuery() };

          var result = await ExecuteQuery(
            schema, @"
            query {
              hero {
                id
                name
              }
            }
          ");
          Console.WriteLine(result);
        }

      private static async Task<string> ExecuteQuery(
        Schema schema,
        string query,
        object rootObject = null,
        string operationName = null,
        Inputs inputs = null)
      {
        var executer = new DocumentExecuter();
        var writer = new DocumentWriter(indent: true);

        var result = await executer.ExecuteAsync(schema, rootObject, query, operationName, inputs);
        return writer.Write(result);
      }
    }

    public class Droid
    {
      public string Id { get; set; }
      public string Name { get; set; }
    }

    public class StarWarsQuery : ObjectGraphType
    {
      public StarWarsQuery()
      {
        Name = "Query";
        Field<DroidType>(
          "hero",
          resolve: context => new Droid { Id = "1", Name = "R2-D2" }
        );
      }
    }

    public class DroidType : ObjectGraphType
    {
      public DroidType()
      {
        Name = "Droid";
        Field<NonNullGraphType<StringGraphType>>("id", "The id of the droid.");
        Field<StringGraphType>("name", "The name of the droid.");
        IsTypeOf = value => value is Droid;
      }
    }
}
```
I also just updated the readme to have that code sample, which can just be copy-pasted into a project and ran.

**Comment by kamil-mrzyglod** [comment]
@joemcbride Splendid!

**Pull request merged**
