### PR TITLE
Super Cool new dB 2 GraphQL.Net Generator

### PR DESCRIPTION
**Pull request by MeaningOfLights**
I started this project last week and over the coming weeks I'll add some more drivers (Oracle, MySql) and a few more Test Databases to demo different dB design paradigms.

### CODE REVIEW

**Comment by sungam3r** [comment]
@MeaningOfLights I see that repo from link is a fork of another repo. Why so?

**Comment by sungam3r** [comment]
@Shane32 Alas 
изображение

**Comment by MeaningOfLights** [comment]
Sorry, let me do this again. Without a Fork. And since it generates C# Classes and Projects (not GraphQL Schema's) I'll add it another another section.

**Comment by Shane32** [comment]
It would appear that all of the generated code applies to HotChocolate, not GraphQL.NET.

**Pull request closed without merging**
