### PR TITLE
Disable MSVS Nuget feed on Windows build

### PR DESCRIPTION
**Pull request by sungam3r**
Helps to investigate #2422

### CODE REVIEW

**Comment by sungam3r** [comment]
@Shane32 I suggest to merge PR and see what happens. If after one-twoo months error will not happen again, then I can remove unnecessary steps and keep only one step that disables MSVS feed.

**Comment by Shane32** [comment]
Have you tested a failure yet? If not, I suggest simulating an error by replacing “dotnet restore” in the first step with “exit 1”. Be sure the workflow runs properly, continuing to execute after the workflow step fails, retrying to restore the packages. I’m not sure, but you may need another setting in there to make it continue. 

If you’ve tested it, sure I’m fine with some extra steps to see if it helps.

**Comment by sungam3r** [comment]
Actually I think that retry step is not necessary at all because of removal of the problem feed.

**Comment by sungam3r** [comment]
I removed not necessary steps. Remember to ping me if one of your builds fails again with NU1102.

**Pull request merged**
