### PR TITLE
Spike on supporting multi-cased fields and aliases

### PR DESCRIPTION
**Pull request by joemcbride**
#275

### CODE REVIEW

**Comment by joemcbride** [comment]
Thoughts on this @tlil @jquense @pravinhabbu4u ?

Other idea I have is having a static class with these options.  That way the option wouldn't have to be passed from class to class.  Also with this implementation the "real" field name isn't determined until after the Schema is initialized.

**Comment by pravinhabbu4u** [comment]
@joemcbride Thanks for the quick response. I tried running a test using casing branch but I was not able to query/ see output in user defined case. Am I supposed to pass an additional parameter while registering fields OR need to override something in my implementation.

**Comment by joemcbride** [comment]
@pravinhabbu4u you will need to change the default FieldNameConverter on the config options of ExecuteAsync.  There is a PascalCaseFieldNameConverter and a DefaultFieldNameConverter.  You probably want the "default" one.  Currently the CamelCaseFieldNameConverter is registered as the default.  You can also implement your own IFieldNameConverter.

**Comment by pravinhabbu4u** [comment]
@joemcbride This is great. I was able to run a quick test and achieve required results. Now I can now even have case sensitive fields
image

**Comment by joemcbride** [comment]
@pravinhabbu4u Great to hear!  I need to do a little more testing on it and I'll wait for any other feedback.

**Comment by pravinhabbu4u** [comment]
@joemcbride Sounds good. Thanks for your quick assistance. I hope new options will be available via nuget package soon.

**Comment by tlil** [comment]
@joemcbride Sounds good to me. Might be a good idea to add a unit test to ensure that aliases aren't affected by `IFieldNameConverter`'s?

**Comment by jquense** [comment]
sounds reasonable to me. might want to use more robust utils for the included case manipulations to cover a bit more edge cases. I'm partial to https://github.com/jquense/String utils :P

**Comment by joemcbride** [comment]
@tlil Good idea to add more for those.  We have at least one or two tests that have aliases, though nothing that does checks around casing.

**Comment by joemcbride** [comment]
@jquense Looks like your `StringUtils` library strips `_` so that messes with fields like `__type`. 😞

**Comment by pravinhabbu4u** [comment]
In case anyone is looking for Default/ Pascal field name converter then use _.FieldNameConverter option on execute async:
`            return await new DocumentExecuter().ExecuteAsync(_ =>
            {
                _.Schema = schema;
                _.Query = graphqlRequest.Query;
                _.Inputs = inputs;
                _.FieldNameConverter = new DefaultFieldNameConverter();
            }).ConfigureAwait(false);`

**Pull request merged**
