### PR TITLE
Add forgotten ConfigureAwait(false)

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Comment by Shane32** [comment]
That’s all great but we really should apply all these changes to master.

**Comment by sungam3r** [comment]
I intentionally made changes to `develop`. The main development goes there, and not on the `master`. I do not want to perform double work.

**Comment by Shane32** [comment]
I intend to support v4 until v5 is released, and perhaps after for critical bugs.  This is a v4 bug, and can be a critical bug.  It should be in v4.  There would have been no "double work" if this was merged to master.  As it is, now there is, since I have to recreate this PR for v4.

**Comment by sungam3r** [comment]
2 changed files after #2770

**Review by Shane32 — APPROVED** [review]

**Pull request merged**
