### PR TITLE
Reduce memory usage by making shared instances static. 

### PR DESCRIPTION
**Pull request by SebastianStehle**
Useful when you have multiple graphql schemas (I have hundreds).

### CODE REVIEW

**Comment by sungam3r** [comment]
These fields are not `static` intentionally. We intend to make it possible to replace built-in and "system" (provided by GraphQL.NET) scalars. Static fields will not allow this for individual schemas. @Shane32 ?

**Comment by Shane32** [comment]
Correct.  Those instance are mutable, which causes a problem if there were two schemas configured on a single app.  What happens is that when the schema is initialized, the `ResolvedType` properties are set on the graph types, which will overwrite the values in the static instance.  Other issues are also possible, such as field middleware applying to a static instance repeatedly upon each initialization of a schema.

**Comment by Shane32** [comment]
As it applies here, although the list is readonly, the instances contained therein must not be shared between schemas.  So the list cannot be static.

**Comment by SebastianStehle** [comment]
Okay, this is interesting, you can close it now. What can I not share? I am creating graphql types on the fly for my headless CMS and I issues with memory usage and graphql is a big part of the allocations. Therefore I try to reduce as many instances as possible. 

I resolve all types manually, but now I am worried about the middleware thing you mentioned.

**Comment by Shane32** [comment]
The scalar graph types are immutable classes, I believe.  They could be overridden, but the default implementation is immutable.  This presents an opportunity for using static instances, and in this case, perhaps `_builtInScalars` could also be static.  I'd have to check further.

**Comment by sungam3r** [comment]
@SebastianStehle We are preparing v4, in which the memory consumption has decreased quite significantly. Can you provide some working sample code to demonstrate your memory consumption scenario?

**Comment by Shane32** [comment]
> @SebastianStehle We are preparing v4, in which the memory consumption has decreased quite significantly. Can you provide some working sample code to demonstrate your memory consumption scenario?

@sungam3r FYI, we can now benchmark schema build time and memory consumption, which is what I believe @SebastianStehle is trying to help with.  Although many objects are unused after the schema build process (and garbage collection), this PR would reduce the static memory use even after that is complete.  It would be great if we could benchmark the amount of memory in use after garbage collection is complete, but I'm not sure how to do that with the benchmarks.  I could add a console app that uses `GC.Collect` and `GC.GetTotalMemory` if that is what you are looking for, but it may not provide reliable values.  What kind of sample did you have in mind?

**Comment by SebastianStehle** [comment]
Btw: One of the main sources of memory usage (but not allocations of course) is the Metadata Provider. Even for small schemas it takes 1-2 MB for all the ConcurrentDictionary instances. I am cleaning all metadata now to get the memory usage down.

**Pull request closed without merging**
