### PR TITLE
Add test for variable coercion

### PR DESCRIPTION
**Pull request by sungam3r**
Small test to verify behavior for variable coercion and error for wrong literal.

### CODE REVIEW

**Comment by sungam3r** [comment]
At first glance, it seems strange why one request works, and the second does not. This question came up on one of our development teams.

**Comment by sungam3r** [comment]
Well, in fact, everything is a little more interesting. See https://github.com/graphql/graphql-js/issues/1324
@Shane32 I remember you wondered at some places in code when serializing / passing scalars. It seems this is exactly the case. Good candidate for 3.2 milestone.

**Comment by sungam3r** [comment]
If you want, then I can merge this test for 3.1 and then in 3.2 we will "fix" it. We can also defer this PR to 3.2 and make corrections right here.

**Comment by Shane32** [comment]
> If you want, then I can merge this test for 3.1 and then in 3.2 we will "fix" it. We can also defer this PR to 3.2 and make corrections right here.

I’d probably at least add a todo note that this is unintended or incorrect behavior. 

The way I’m planning to fix this will probably be breaking and need to be in 4.0. I can explain later. Maybe a patch could be implemented for 3.2. Good to have this test though.

**Comment by Shane32** [comment]
@sungam3r I suggest we merge this test.  It may be useful when I start reworking the input code.

**Review by Shane32 — APPROVED** [review]

**Pull request merged**
