### PR TITLE
Fix for "Location of errors is always line:0, column:0"

### PR DESCRIPTION
**Pull request by cdroulers**
This crashes Relay in https://github.com/facebook/relay/blob/17096c3f22fbd98d0b4ace26762917e6c6a54832/src/network-layer/default/RelayDefaultNetworkLayer.js#L185 since the line number is 0. The line is then undefined and `substr` fails with an undefined error.

From what I can tell, [DocumentExecuter](https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Execution/DocumentExecuter.cs#L58) never has line or column on `SourceLocation` (I inspected the object in the debugger).

It seems to always be zero because of [this](https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Language/CoreToVanillaConverter.cs#L305).

Here is a first draft of a fix. Is this right? 

I think my `should_calculate_line_and_column` test should probably be elsewhere, but I'm not sure where it belongs!

Thanks again for the great library!

(I'll rebase everything into a neat commit once reviewed and approved!)

### CODE REVIEW

**Comment by cdroulers** [comment]
There seems to be a mention of location in this comment: https://github.com/graphql-dotnet/graphql-dotnet/pull/127#issuecomment-237761918

**Comment by joemcbride** [comment]
That converter should show line numbers with the AST values.  I think we probably just need to add some line numbers for when the exception is thrown, which is outside that Document parser.  We should probably be able to get the numbers from the associated AstNode.

**Comment by cdroulers** [comment]
I'm not sure where to look, any pointers on where to look more specifically?

**Comment by joemcbride** [comment]
Tracking them down.  I think there are a few places - essentially anywhere there is a `try/catch`.

**Comment by joemcbride** [comment]
Here are the places I've found where it could be a problem.  Not all of them have access to a Node that would have a specific line/column though.  In that case we may just want to default to 1/1.

* https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Execution/DocumentExecuter.cs#L93
* https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Execution/DocumentExecuter.cs#L116
* https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Execution/DocumentExecuter.cs#L430
* https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Execution/DocumentExecuter.cs#L433

**Comment by cdroulers** [comment]
If I remove the code I changed in `WithLocation`, the nodes don't have proper line / column information.

Here is a screenshot of the debugger at `DocumentExecuter:205`.

image

If I understand correctly, I can add the location in a few places you pointed out, but I need to keep my code which calculates the line/column. Maybe I can make that code evaluate lazily in SourceLocation or something like that so the computation isn't done for *every* node of the AST and only when an error occurs?

**Comment by cdroulers** [comment]
I could also make the `AddLocation` return `this` so it would be one line to throw an error and not 3.

```csharp
var error = new ExecutionError("Schema is not configured for mutations");
error.AddLocation(operation);
throw error;
```

Becomes
```csharp
throw new ExecutionError("Blah").WithLocation(operation);
```

**Comment by joemcbride** [comment]
Yes, the intent was it would only be calculated when an error occurred.  There is some awkwardness there that happened with the move to the new lexer/parser.  I would eventually like to update the lexer/parser to keep track of the line/column so it wouldn't have to be calculated.

There is a `Location` class from `GraphQL-Parser` that will do the line/column calculation, which is being used in the `ValidationError` class.  I missed updating the `ExecutionError` class when that change happened.

There is an `OriginalQuery` property on the `Document` class that can be used to get the Query.  It may be useful to add that to the `ExecutionContext` if needed.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/ValidationError.cs#L32-L33

```
var location = new Location(new Source(originalQuery), n.SourceLocation.Start);
AddLocation(location.Line, location.Column);
```

The `WithLocation` is currently used to just add a `SourceLocation` object to a `Node`.  For exceptions there are two `AddLocation` methods.

**Comment by cdroulers** [comment]
I was just figuring all that out as your message came in. I'll look at ValidationError! commit incoming!

**Comment by cdroulers** [comment]
To have the `document.OriginalQuery` in most of the places where `.AddLocation` is called, I have to modify a lot of methods to pass the document all the way down. Is that acceptable?

**Comment by joemcbride** [comment]
Looking at the usages, I *think* if you add a `OriginalQuery` property to `ExecutionContext`, or just add the `Document` to the `ExecutionContext`, I think that would make it a little less cumbersome.

**Comment by cdroulers** [comment]
I had to fix indentation in CoreToVanillaConverter back to what it was. Visual Studio indented all the switch/case curly brackets one level for some reason. Can't find the setting. Anyway, it's fixed and everything has a test!

**Comment by joemcbride** [comment]
👍 This is a case where I wish it could be done with less code but I think it's the right decision performance wise.

**Comment by cdroulers** [comment]
Does github do automatic rebasing now?

**Comment by joemcbride** [comment]
Not automatic, but you can choose squash and merge or rebase and merge when merging a PR.

**Comment by cdroulers** [comment]
Sweet! Good to know!

**Pull request merged**
