### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/graphql-dotnet ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by SimonCropp** [comment]
Curious who creatthe open collective? Would like to get on a call and have a chat about the postives and negatives

**Comment by SimonCropp** [comment]
@joemcbride need any help with this?

**Comment by sungam3r** [comment]
It looks like stale. Closing?

**Comment by sungam3r** [comment]
@joemcbride @Shane32 I think it's worth merge thi PR. A few lines of additional information won't hurt. I resolved conflicts and formatted the readme slightly.

**Comment by sungam3r** [comment]
Regarding failed labeler see https://github.com/actions/first-interaction/issues/10#issuecomment-616217951 and https://github.com/actions/labeler/pull/50

**Review by Shane32 — APPROVED** [review]
My only comment is that the link to the documentation should be prominently displayed near the top of the readme.  Right now it's "on page 2".  Outside the scope of this PR, I know, but just saying.

**Comment by sungam3r** [comment]
Moved. I will change readme again in separate PR.

**Pull request merged**
