### PR TITLE
Switch to Nullability.Source

### PR DESCRIPTION
**Pull request by sungam3r**
изображение

### CODE REVIEW

**Comment by sungam3r** [comment]
@Shane32 By the way I always have some issues with NullabilityInfo package when working locally in VS 2022
изображение
The same for this new package. `dotnet build` from console works fine.
изображение
ping @SimonCropp

**Comment by Shane32** [comment]
@sungam3r I have no problems with the VS IDE in this respect on any of my computers.  Is there any chance that you have set `SingleTestPlatform` and this is causing this issue?  (Just guessing because I can't think of any other reason.)

Peeking at the definition for me properly shows either the .NET reference or the NullabilityInfo instance depending on the platform selection in the dropdown.

image

**Comment by Shane32** [comment]
This PR seems to work fine also for me.

image

**Review by Shane32 — APPROVED** [review]

**Comment by Shane32** [comment]
Note that I have been using VS 2022 awhile and am using 17.3.2 now

**Pull request merged**
