### PR TITLE
Add analyzer pages to the sitemap

### PR DESCRIPTION
**Pull request by gao-artur**

### CODE REVIEW

**Review by Shane32 — APPROVED** [review]

**Comment by gao-artur** [comment]
@Shane32 the docs still don't work. Can you check, please?
https://graphql-dotnet.github.io/docs/analyzers/Overview/

**Comment by Shane32** [comment]
Sure. Little busy now but I'll check it out.

**Comment by gao-artur** [comment]
It seems to work when I change the url to all lower case letters.

**Comment by Shane32** [comment]
Go ahead and make a PR and merge it then. Docs will change immediately without having to issue a release.

**Comment by Shane32** [comment]
The docs use gatsby I think to create the static site. I didn’t set it up and have not really used gatsby much myself other than to add or update docs here.

**Pull request merged**
