### PR TITLE
Fix reader.Skip and add test

### PR DESCRIPTION
**Pull request by Shane32**

### CODE REVIEW

**Comment by Shane32** [comment]
Didn't realize that the one serializer already pointed to the next token, so advancing it again was improper.  In either case, however, Skip automatically advances it if it's pointing to the property name, so do need for Read.

**Comment by Shane32** [comment]
Thought I had a test for this, but it didn't catch it properly.

**Comment by sungam3r** [comment]
I was also interested in calling `Read`, when I looked through code. I thought that since the tests passed, everything was fine and did not ask.

**Comment by Shane32** [comment]
> I was also interested in calling `Read`, when I looked through code. I thought that since the tests passed, everything was fine and did not ask.

Correct for one but not the other.... but not needed for either.

**Pull request merged**
