### PR TITLE
Introduce file scoped namespaces [DEMONSTRATION]

### PR DESCRIPTION
**Pull request by sungam3r**
See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

For the demonstration I chose two projects in which conflicts should not arise with other PRs.

1 indentation saved! 😮 

Looks unusually IMO.

### CODE REVIEW

**Comment by Shane32** [comment]
Excellent!  As you create PRs, please add a comment if you change any code other than as described above, as it can be difficult to read the diff.  (The "hide whitespace" option works pretty well, though.)

However..... if you change this, whether it is in develop or master, we cannot merge from master to develop without EVERY changed file showing as a conflict.  (I think).  We may want to delay this change until after v5 is released and we only need to worry about the master branch.  Otherwise, I would suggest we merge this to develop, to ease merge conflicts.

Thoughts?

**Comment by sungam3r** [comment]
I thought about conflicts. In fact, I do not have a lot of desire to merge this PR. Perceive it is more like a demonstration and "feature reminder". It is better to finish the main work with feature-PRs first, and then engage in "code decorating" (although main work apparently never end 🤔).

**Comment by Shane32** [comment]
@sungam3r Please note that I will be on the road for the next few days, so I may be a little slow to respond, but I'll try to review your PRs promptly as I'm able.

**Comment by sungam3r** [comment]
There were conflicts, let's not do so more untill merging develop into master.

**Pull request merged**
