### PR TITLE
Fix SchemaTypes so it does not create instances twice

### PR DESCRIPTION
**Pull request by Shane32**
Fixes:
- #3100

### CODE REVIEW

**Comment by Shane32** [comment]
@sungam3r `SchemaTypes` might still be a mess, but at least this bug should be fixed for now.  I also intend to release 5.2 once this PR is merged, unless you have an objection.

**Comment by Shane32** [comment]
@sungam3r Any comments here?

**Comment by Shane32** [comment]
@sungam3r I will be merging this PR tonight and releasing 5.2.  Please let me know if you have any comments.

**Comment by sungam3r** [comment]
OK. I looked through the code and I understand the described problem slightly.

**Comment by sungam3r** [comment]
Why did not you change line 429 as well ?
изображение

**Pull request merged**
