### PR TITLE
Remove TypeExtensions.As

### PR DESCRIPTION
**Pull request by Shane32**

### CODE REVIEW

**Review by sungam3r — APPROVED** [review]

**Review by sungam3r — CHANGES_REQUESTED** [review]
@Shane32  see  `internal static class SchemaExtensions.As`. I did it on purpose to fix the LGTM warnings. I just forgot to write `this` so this method was not used 🤦

**Comment by Shane32** [comment]
I can't find `SchemaExtensions.As`.

Faulty LGTM warnings is not an excuse for bad code.  Writing an alias for `as` that does the same thing as `as` is bad code.

**Comment by Shane32** [comment]
You can probably put some type of comment at the top of the file to have lgtm ignore that specific warning, if you're concerned about it.

**Comment by Shane32** [comment]
I see you approved the changes, so I'll merge it.  I'm not sure if you wanted other changes here, but if so, we can just make them in another PR.

**Comment by sungam3r** [comment]
> I can't find SchemaExtensions.As.
https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/src/GraphQL/Utilities/SchemaBuilder.cs#L538

**Pull request merged**
