### PR TITLE
Add global switches

### PR DESCRIPTION
**Pull request by sungam3r**
Inspired by https://github.com/graphql-dotnet/graphql-dotnet/pull/1451#issuecomment-768395522 😄 

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.14393.3986 (1607/AnniversaryUpdate/Redstone1)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=3515611 Hz, Resolution=284.4456 ns, Timer=TSC
.NET Core SDK=5.0.102
  [Host]     : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
  DefaultJob : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT


```
|Method|Stage|Mean [base]|Mean [current]|Mean [% of base]|Allocated [base]|Allocated [current]|Allocated [% of base]|
|---|---|--:|--:|--:|--:|--:|--:|
|Introspection|Build|6,212,182.516 ns|1,329,152.997 ns|<span style="color:green">21</span>|2639115 B|323648 B|<span style="color:green">12</span>|
|Introspection|Parse|19,849.585 ns|19,144.244 ns|<span style="color:green">96</span>|11920 B|11920 B|100|
|Introspection|Convert|10,586.301 ns|10,702.795 ns|<span style="color:red">101</span>|16552 B|16552 B|100|
|Introspection|Validate|200,317.036 ns|196,974.775 ns|<span style="color:green">98</span>|11104 B|11104 B|100|
|Introspection|DeserializeVars|1.528 ns|1.763 ns|<span style="color:red">115</span>|-|-|-|
|Introspection|ParseVariables|3.569 ns|3.163 ns|<span style="color:green">88</span>|-|-|-|
|Introspection|Execute|768,061.684 ns|771,362.559 ns|100|319177 B|319179 B|100|
|Introspection|Serialize|124,417.597 ns|120,670.790 ns|<span style="color:green">96</span>|27920 B|27921 B|100|
|||||||||
|Hero|Build|6,209,011.244 ns|1,336,174.210 ns|<span style="color:green">21</span>|2638812 B|323151 B|<span style="color:green">12</span>|
|Hero|Parse|928.082 ns|944.719 ns|<span style="color:red">101</span>|784 B|784 B|100|
|Hero|Convert|556.819 ns|532.943 ns|<span style="color:green">95</span>|1056 B|1056 B|100|
|Hero|Validate|12,471.502 ns|12,790.602 ns|<span style="color:red">102</span>|2464 B|2464 B|100|
|Hero|DeserializeVars|1.539 ns|1.743 ns|<span style="color:red">113</span>|-|-|-|
|Hero|ParseVariables|3.410 ns|3.323 ns|<span style="color:green">97</span>|-|-|-|
|Hero|Execute|2,400.086 ns|2,757.077 ns|<span style="color:red">114</span>|2264 B|2264 B|100|
|Hero|Serialize|598.848 ns|604.057 ns|100|544 B|544 B|100|
|||||||||
|Variables|Build|5,589,446.851 ns|1,057,560.111 ns|<span style="color:green">18</span>|2530635 B|245224 B|<span style="color:green">9</span>|
|Variables|Parse|1,782.323 ns|1,783.178 ns|100|1008 B|1008 B|100|
|Variables|Convert|609.475 ns|593.548 ns|<span style="color:green">97</span>|1208 B|1208 B|100|
|Variables|Validate|23,216.466 ns|23,383.966 ns|100|9865 B|9865 B|100|
|Variables|DeserializeVars|10,909.719 ns|10,937.019 ns|100|8288 B|8288 B|100|
|Variables|ParseVariables|37,489.041 ns|41,341.455 ns|<span style="color:red">110</span>|14886 B|14886 B|100|
|Variables|Execute|3,046.985 ns|3,155.118 ns|<span style="color:red">103</span>|2025 B|2025 B|100|
|Variables|Serialize|437.368 ns|458.499 ns|<span style="color:red">104</span>|544 B|544 B|100|
|||||||||
|Literal|Build|5,596,007.173 ns|1,065,559.777 ns|<span style="color:green">19</span>|2530534 B|245182 B|<span style="color:green">9</span>|
|Literal|Parse|21,404.517 ns|20,741.946 ns|<span style="color:green">96</span>|9016 B|9016 B|100|
|Literal|Convert|8,681.333 ns|9,276.619 ns|<span style="color:red">106</span>|12768 B|12768 B|100|
|Literal|Validate|150,375.099 ns|151,556.793 ns|100|27200 B|27200 B|100|
|Literal|DeserializeVars|1.550 ns|1.751 ns|<span style="color:red">112</span>|-|-|-|
|Literal|ParseVariables|3.534 ns|3.152 ns|<span style="color:green">89</span>|-|-|-|
|Literal|Execute|37,181.117 ns|35,758.958 ns|<span style="color:green">96</span>|14312 B|14312 B|100|
|Literal|Serialize|454.111 ns|436.569 ns|<span style="color:green">96</span>|544 B|544 B|100|

### CODE REVIEW

**Comment by Shane32** [comment]
All of the global configuration settings should be in one place. Let’s move the name validation settings here also.

**Comment by Shane32** [comment]
Would it be better to perform all tests with global settings enabled (even if default is disabled)?

**Comment by Shane32** [comment]
For clarity let’s add = false to each of the static properties, assuming that’s what the new default will be.

**Comment by Shane32** [comment]
I see it’s just xml that’s now false by default. But let’s add = false for that one.

**Comment by sungam3r** [comment]
> Would it be better to perform all tests with global settings enabled (even if default is disabled)?

I think that no. We choose the default values. Whichever we choose, tests need to be performed with these values.

**Comment by sungam3r** [comment]
Done

**Comment by sungam3r** [comment]
After that I will continue to investigate the degradation in #1451.

**Review by Shane32 — APPROVED** [review]

**Comment by Shane32** [comment]
We should probably update migration docs, btw.

**Comment by sungam3r** [comment]
Done

**Pull request merged**
