### PR TITLE
Schema generator

### PR DESCRIPTION
**Pull request by holm0563**
As disused here:
https://github.com/graphql-dotnet/graphql-dotnet/issues/132
https://github.com/graphql-dotnet/graphql-dotnet/issues/14

This automatically generates schema based on c# reflection. This closely follows the spec outlined by @tlil87 and hopefully we can use this as a great starting point on his idea. I know the name SchemaGenerator differs form Conventions but I thought it may be more descriptive.

### CODE REVIEW

**Comment by tlil87** [comment]
That repo has gone thru some major refactoring that I will push beginning of next week. So I fear that this will clash with my more recent changes. Will ping you once I push my work to Conventions.

**Comment by holm0563** [comment]
@tlil87 does your project exist on github?

**Comment by tlil87** [comment]
@holm0563 yes, but haven't pushed any changes yet unfortunately as I wanted to wrap up the refactoring i'm working on (I have a closed-source repo that we've used in production at Hudl for the past 9 months). i will push my changes over the next few days though. the repo will live in graphql-dotnet/conventions.

**Comment by holm0563** [comment]
We are in a similar situation using this in production. I'd like to get this concept starter sooner than later otherwise we will probably run off the forked version for a while. If your solution is closed source it would be quicker to start with this one and move over additional functionality.

**Comment by tlil87** [comment]
I'm literally just making a last few changes when I'm free over the weekend, and then the full library will be released as open-source. So I'm not too concerned about the timing aspect of it :)

**Comment by holm0563** [comment]
I guess I'm not familiar enough with how open source works. Whats the process to merging our two different ideas and making sure we have the best of both worlds moving forward? It definitely makes it difficult when this is closed source and no one else has the ability to contribute. This pull request is supporting our needs for this concept which include over 200 models converting to fields and 50 different queries and mutations.

**Comment by joemcbride** [comment]
@holm0563 Let me clarify a bit.

I have no plans to bring in @tlil87 conventions project to the core project.  Way back when, I created that as a separate repo that he could commit to, since I think conventions are a good idea.

I also have no plans to bring in this new "convention" code to the core project.

Why?  Once its in this repo, I have to support it.  Please don't take offense, though I've been working on this project for a very long time and you've just started contributing (and thank you by the way!).  Though I have no idea how long you're going to stick around.  I don't want to have to support your code yet.  That is a reality of Open Source, especially on a project that only has 1-2 main contributors.

So - this is a perfect thing to have as an add-on to the core project, with a separate nuget package.  I said the same thing to @tlil87 when he was building his last year.

**Comment by tlil87** [comment]
I second that @joemcbride. And @holm0563, I agree, I'd love to work together on this one, so don't get me wrong. And it's great to have more contributors as well :+1: I'm out until the weekend, but will touch base when I'm back.

**Comment by holm0563** [comment]
Thanks for the clarification. I took it as a separate project not repo. I'll continue with that path. @tlil87 let me know when your project is done and hopefully we can come up with one standard approach. Thanks guys!

**Comment by dNetGuru** [comment]
Just out of curiosity.
Is the conventions package published anywhere? What about the schema generator?

**Comment by holm0563** [comment]
The schema generator is under my fork.  Once a few bug fixes are in place I'll move it to a separate project and just include this one as a nugget reference.

**Comment by tlil87** [comment]
@dNetGuru `graphql-dotnet/conventions` is also coming up shortly. there will essentially be two options there until @holm0563 and I potentially look into consolidating our efforts into one.

**Comment by mirhagk** [comment]
Has anything happened here yet?

I'm interested in building an API on GraphQL but I'd really rather using POCOs than what the core requires writing for the schema.

I have a feeling that there's probably a lot of other people in my same position who'd really only consider adopting it if one of these schema generators is up and running, so once one of these options gets published it'd be nice to see a reference to it on the main readme.  (I of course understand the reasoning to have it in a separate package)

**Comment by holm0563** [comment]
@mirhagk Check out https://github.com/holm0563/graphql-schemaGenerator

**Comment by joemcbride** [comment]
I'm going to go ahead and close this now as we have links to your project in the docs.  Thanks for your work!

**Pull request closed without merging**
