### PR TITLE
Only net5 for local tests

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Review by Shane32 — COMMENTED** [review]
Why would you do this?  I always want all the platforms to test locally.  I certainly would want to if we ever ran into an issue.  If you want to run a single platform, click on that platform and hit run.

I suggest you figure out how to configure your local computer to only run a certain platform, if that's how you want it to work for your PC.  But it should not be default for the repo.

**Comment by Shane32** [comment]
By the way, we have had multiple issues that only applied to a single platform.  This would be very annoying to debug if we had to mess with the setting every time we wanted to run on .NET 3 / 5 / 2.2

**Comment by sungam3r** [comment]
I am not comfortable with choosing some platforms every time. In addition, due to many platforms, test detection is slower, noticeably slower. I can make all platforms default and replace one setting locally.

**Comment by Shane32** [comment]
> I am not comfortable with choosing some platforms every time. In addition, due to many platforms, test detection is slower, noticeably slower. I can make all platforms default and replace one setting locally.

Just configure a local github setting to ignore a config file if you want it different.  The projects in the repo should be configured for all the supported platforms.

**Comment by sungam3r** [comment]
Done. What is "local github setting" ?

**Comment by Shane32** [comment]
e.g. `Directory.Build.local.Props`.  Then you can set it however you want in there.

**Comment by Shane32** [comment]
Edit `.gitignore` to ignore `Directory.Build.local.Props`.  Configure `Directory.Build.Props` to import `Directory.Build.local.Props`

**Comment by sungam3r** [comment]
Did you mean  _git_ settings?

**Comment by Shane32** [comment]
something like that.  then you can add the file to your local machine, and it will always be ignored no matter what branch you're in,etc.

**Comment by Shane32** [comment]
> Did you mean _git_ settings?

yes

**Comment by sungam3r** [comment]
Done

**Review by Shane32 — APPROVED** [review]

**Pull request merged**
