### PR TITLE
CodeQL support

### PR DESCRIPTION
**Pull request by sungam3r**
This is a success! 😄 
изображение

After 75badfc:
изображение

### CODE REVIEW

**Comment by Shane32** [comment]
Can it be updated so that it does not analyze the tests?

**Comment by sungam3r** [comment]
I think yes, but why not to analyze tests? Let's analyze all C# code.

**Comment by sungam3r** [comment]
I added config file to try include/exclude paths.

**Comment by sungam3r** [comment]
From docs:
> For compiled languages, if you want to limit code scanning to specific directories in your project, you must specify appropriate build steps in the workflow. The commands you need to use to exclude a directory from the build will depend on your build system. 

I read the documentation and so I understand that in our case we do not even need to build test projects.

**Comment by sungam3r** [comment]
@Shane32 Are you sure that the tests should be excluded?

**Comment by sungam3r** [comment]
изображение

**Comment by Shane32** [comment]
I find it quite annoying to have to write tests that conform to all the coding standards as the main project. There’s no reason for it. The test is there simply to ensure the main project works properly. Each test is, generally, independent, and new tests can be written without any regard to existing tests. 

I’m not sure what codeql does but that’s my general thoughts. So if we want codeql analysis as warnings in the tests that’s fine but I’m not sure we should have it required to pass build checks. Perhaps if I knew how codeql was useful then maybe I would have another opinion. 

I also do not think we should merge this PR until it passes all build checks, showing a green checkmark by the build. Perhaps one option is to configure all the codeql tests as warnings only, until the errors can be fixed.

**Comment by sungam3r** [comment]
> I’m not sure we should have it required to pass build checks.

CodeQL has never been mandatory to merge PR.

**Comment by Shane32** [comment]
> > I’m not sure we should have it required to pass build checks.
> 
> CodeQL has never been mandatory to merge PR.

Regardless, it shows a red x by the build now.

**Comment by Shane32** [comment]
When we added xml comments, we selectively enabled the xml warnings once we had the xml comments in place. We didn’t configure the build to fail when an xml comment was missing until all xml comments were in place.

**Comment by sungam3r** [comment]
What do you think about single error left ? https://github.com/graphql-dotnet/graphql-dotnet/security/code-scanning/645?query=ref%3Arefs%2Fpull%2F2717%2Fmerge+ref%3Arefs%2Fpull%2F2717%2Fhead+ref%3Arefs%2Fheads%2Fcodeql

**Comment by sungam3r** [comment]
Base `GraphType` overrides `Equals(object)` so I think to mark error as false positive.

**Comment by Shane32** [comment]
Right, or we can probably change the code easily to prevent the false positive.

**Comment by Shane32** [comment]
> Base `GraphType` overrides `Equals(object)` so I think to mark error as false positive.

Makes sense

**Comment by sungam3r** [comment]
изображение

🎉

**Comment by sungam3r** [comment]
The last question - add or not into branch protection rules ?

**Comment by Shane32** [comment]
Well I wouldn’t just now probably.

**Review by Shane32 — APPROVED** [review]

**Pull request merged**
