### PR TITLE
Dataloader optimizations

### PR DESCRIPTION
**Pull request by johnrutherford**
Issue #795 got me looking at the DataLoader code again. I realized that the use of `ContinueWith()` in `DataLoaderBase.Dispatch()` was making it so that continuations were always run on the `ThreadPool`. So it was causing more threads to be used even when it was completely unnecessary like if the `Task` was already completed. 

So I re-wrote `Dispatch()` and `DispatchAll()` to use `async`/`await`. This results in less threads being used and improved performance. 

I also improved the DataLoader unit tests, and added a large query test that I used for profiling.

### CODE REVIEW

**Comment by johnrutherford** [comment]
@joemcbride, looks like the AppVeyor build failed when downloading yarn packages (unrelated to my changes). Are you able to manually trigger a new build?

**Comment by BenjaBobs** [comment]
IIRC, if you close and re-open the PR a new build will trigger.

**Comment by cotzo** [comment]
Hey. Any ETA for when this will be published so we can also have #812?

Thanks

**Comment by huysentruitw** [comment]
Any idea when this gets released? I'm currently running into dead-lock issues with dataloader in 2.1.0 when calling EF Core queries with async/await. When I call everything synchronously and return `Task.FromResult` everywhere, I don't have the dead-lock issue. I wonder if the changes in this pull-request affect this behavior.

**Comment by johnrutherford** [comment]
@huysentruitw, these changes are unlikely to make a difference if you’re having deadlocks. Can you open up a new issue with some more details and tag me? I can try and help you there.

**Comment by huysentruitw** [comment]
You can check-out this branch: https://github.com/huysentruitw/conventions/tree/sample/dataloader-efcore

I am using the DataLoader implementation in combination with the GraphQL Conventions library, but that shouldn't make any difference here.

Currently, the repositories use sync calls to EF Core and what I see is that I can query first and second level data with these GraphQL queries:

First level:

```
query AllMovies {
  movies {
    id
    title
    genre
    releaseDateUtc
  }
}
```

Second level:

```
query AllMovies {
	movies {
    id
    title
    genre
    releaseDateUtc
    
    actors {
      id
      name
    }
  }
}
```

But as soon as I add a third level to the query, the thing deadlocks:

```
query AllMovies {
	movies {
    id
    title
    genre
    releaseDateUtc
    
    actors {
      id
      name
      
      country {
        code
        name
      }
    }
  }
}
```

The reason is because the `DataLoaderContext.DispatchAll()` method exists before all field resolvers were able to run. I've used similar code in the past with EF6 and .NET 4.7.1 and mostly deadlocks like this were caused by a missing `ConfigureAwait(false)` somewhere (which should no longer be needed because there is no AspNetSyncrhonizationContext for .NET Core). Anyway, in that test project, I've already tried to switch to this dataloader implementation: https://github.com/dlukez/dataloader-dotnet but the results are the same (I had some hope, because that implementation contains it's own synchronization context and task scheduler, but no luck...).

**Comment by huysentruitw** [comment]
I'll try my own DataLoader implementation (https://github.com/huysentruitw/yadi) later today or tomorrow and report back.

**Comment by huysentruitw** [comment]
Sorry to say but, DAMN I'M GOOD! 🙂 

It works fine with my own [YADI](https://github.com/huysentruitw/yadi) implementation! See the Yadi branch: https://github.com/huysentruitw/conventions/tree/sample/yadi

And even with async EF Core calls: https://github.com/huysentruitw/conventions/tree/sample/yadi-async-repos

I think the reason is the while loop, which keeps running and checking for new loaders: https://github.com/huysentruitw/yadi/blob/master/src/Yadi/DataLoaderContext.cs#L49

**Pull request merged**
