### PR TITLE
Remove SchemaFilter and NameConverter from ExecutionOptions

### PR DESCRIPTION
**Pull request by Shane32**
As a step towards making `ISchema` read-only, this PR removes `SchemaFilter` and `NameConverter` from `ExecutionOptions`, which used to simply set the corresponding properties on the schema.  Now the schema's constructor should typically be used to set these properties.

Alternatively, we could move `Filter` and `NameConverter` from `ISchema` to `ExecutionContext`, although this may prove to be difficult to implement.

### CODE REVIEW

**Comment by sungam3r** [comment]
How to set these properties to the calling code now?

https://github.com/graphql-dotnet/server/blob/develop/src/Core/Internal/DefaultGraphQLExecuter.cs#L69
https://github.com/graphql-dotnet/server/blob/develop/src/Core/Internal/DefaultGraphQLExecuter.cs#L71

**Comment by Shane32** [comment]
It should be set in the schema constructor.  I'll update the docs in this PR.  You could of course pull `Schema` from DI and set the properties manually before execution, but the point of this PR is that it's actually improper to do so, as modifying those properties could (in theory) change the execution of another schema executing in parallel.

**Comment by Shane32** [comment]
Actually the docs say nothing about either field, except within the 1.x to 2.x migration guide, which already indicates that the `FieldNameConverter` should be set on the schema.

Of course these changes would be added to the 3.0 migration guide.

**Comment by Shane32** [comment]
Just for reference, the equivalent code (but equally as "wrong" as before) would be:
```
            var schema = Schema;
            schema.SchemaFilter = _options.SchemaFilter ?? new DefaultSchemaFilter();
            schema.NameConverter = _options.NameConverter ?? CamelCaseNameConverter.Instance;
            var opts = new ExecutionOptions
            {
                Schema = schema,
                OperationName = operationName,
                Query = query,
                Inputs = variables,
                UserContext = context,
                CancellationToken = cancellationToken,
                ComplexityConfiguration = _options.ComplexityConfiguration,
                EnableMetrics = _options.EnableMetrics,
                ExposeExceptions = _options.ExposeExceptions,
                UnhandledExceptionDelegate = _options.UnhandledExceptionDelegate,
            };
```

**Comment by sungam3r** [comment]
`ExecutionOptions` contains many other properties. Why did you choose only these?

**Comment by Shane32** [comment]
They are the only ones that modify the schema.  The other options are stored within `ExecutionContext`.

**Comment by Shane32** [comment]
Well, the FieldMiddleware also modifies the schema.  But it only does so once ever, and then the schema is locked.....  Thoughts?

**Comment by Shane32** [comment]
Come to think of it, I don't think there are any locks while initializing the middleware or schema.  It is entirely possible that the middleware could be applied twice if two DocumentExecuters started executing simultaneously on an uninitialized schema.

**Comment by Shane32** [comment]
If we can get to a point where ISchema is read-only, it would help prevent these types of issues from unintentionally getting into the codebase.

**Comment by Shane32** [comment]
@sungam3r I really feel that these particular options belong on the schema, as they change and define the schema versus the execution.  Middleware falls in the same boat.  However, it's not going to make any practical different to users if you'd rather not make these changes.  Feel free to close this PR if you wish.

**Comment by sungam3r** [comment]
I have now looked again at the code. I don't like the fact that every time we execute a request, we create a new ExecutionOptions instance, set the schema to it, and then inside ExecuteAsync we fill the schema properties with the properties from the options. This in itself causes some confusion. Second, there are potential problems with the singleton schema. Perhaps more serious refactoring is needed, not just the elimination of a couple of properties. I don't know how to do it yet.

**Comment by Shane32** [comment]
Well, this would be a start....

**Comment by sungam3r** [comment]
I would also like to point out that any get/set property on the `Schema` potentially leads to a problem when using the schema as a singleton if we one way or another expose schema via `ExecutionOptions`, where caller may set different values each request. It is possible that it simply does not make sense to protect yourself from such problems, this is a fight against windmills.

**Comment by Shane32** [comment]
I agree, which is why a read-only schema really should be best.  It just changes a whole lot of code.  In this particular instance, I can set `ISchema.NameConverter` and `ISchema.Filter` to be read-only; but there's still a bunch of other read/write properties on the schema.

**Review by joemcbride — APPROVED** [review]

**Comment by Shane32** [comment]
Let’s merge this into a new develop branch for 4.0 changes, as this would be a breaking change for 3.x

**Comment by sungam3r** [comment]
I will review this again next days.

**Review by sungam3r — APPROVED** [review]
Let's see how it turns out.

**Pull request merged**
