### PR TITLE
Updates.

### PR DESCRIPTION
**Pull request by sioanis**
To Do: 

- [ ] Change the base branch from `master` to `main`.

### CODE REVIEW

**Comment by sungam3r** [comment]
What is the goal?

**Comment by sioanis** [comment]
The goal is to complete the to-do before merging.

**Comment by sioanis** [comment]
I created a fork to try this out.

**Comment by sungam3r** [comment]
I mean what is the goal to rename master into main?

**Comment by sioanis** [comment]
Yes.

**Comment by sungam3r** [comment]
Sorry. Perhaps I was not clear, I am not a native speaker. My question is **why** to rename master in main at all?

**Comment by sioanis** [comment]
Old pepper doesn't like this. We should keep the branch.

Screen Shot 2022-02-20 at 3 12 40 PM

**Comment by sungam3r** [comment]
😕 I do not know who it is. Probably his opinion is important for you. Well, OK.

**Comment by sioanis** [comment]
This is the Github reasoning for renaming. (https://github.com/github/renaming)

**Comment by sioanis** [comment]
Whoever has the name old pepper probably has some good ideas.

**Comment by sungam3r** [comment]
Thanks. I briefly read this documentation, but nevertheless I did not understand what is the reason. There is described **what** is changing and **where**, but it does not say **why** this is done. The only proposal from that document that should answer this question (as I think) sounds so
> We like it because it's short, it keeps your muscle memory intact, and it translates well across most languages.

I can say the same thing about `master`. Taking into account the amount of work to be done in addition to renaming (change  all CI workflows, change settings of git clients) and the dubiousness of the above arguments, I would not rename branch. In addition, following this renaming it needs to be performed in all the repositories of the graphql-dotnet org to have the same structure in all repos.

**Comment by sioanis** [comment]
Sounds good.

**Pull request closed without merging**
