### PR TITLE
Update query-validation.md

### PR DESCRIPTION
**Pull request by assilabdulrahim**
CoreRules is a property, should not be used as a method.
I deleted the parentheses

### CODE REVIEW

**Review by sungam3r — APPROVED** [review]

**Comment by sungam3r** [comment]
@Shane32 https://github.com/graphql-dotnet/graphql-dotnet/runs/1306003114?check_suite_focus=true
```
Pushing to https://***@github.com/graphql-dotnet/graphql-dotnet.github.io.git:master
fatal: could not read Password for 'https://***@github.com': No such device or address
```

**Comment by Shane32** [comment]
It won’t publish until the PAT is added to the secrets. I can’t add a valid PAT until “graphqlbot” is part of the team. If you can’t invite the account then we need to wait for @joemcbride 

I did test the publishing process with my token. It worked; then I deleted the token. 

Once the token is added we can re-run the workflow.

**Comment by assilabdulrahim** [comment]
No problem.
Thank you for the information.

**Comment by sungam3r** [comment]
> If you can’t invite the account then we need to wait for @joemcbride

Apparently yes.

**Comment by Shane32** [comment]
Docs updated.

**Comment by sungam3r** [comment]
Excellent

**Pull request merged**
