### PR TITLE
Remove Arguments initialization from FieldBuilder

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Review by Shane32 — APPROVED** [review]

**Comment by Shane32** [comment]
@sungam3r Surprisingly enough, this broke a bunch of my code.  No big deal, but perhaps we should update the migration document in case other people have code like mine.

**Comment by sungam3r** [comment]
Example?

**Comment by Shane32** [comment]
Nothing I can share.  It was just code that created a field with a field builder, and then passed the FieldType instance to some other code which attempted to add an argument.

**Comment by Shane32** [comment]
Just saying that sometimes the things you wouldn't expect to have any outside effect, does.

**Pull request merged**
