### PR TITLE
741 more scalar types

### PR DESCRIPTION
**Pull request by KoditkarVedant**
Enhancement:- #741
 
- Added ScalarGraphType for following types
  - [x] Short
  - [x] UShort
  - [x] UInt
  - [x] ULong
  - [x] Guid
- Added test cases.

### CODE REVIEW

**Comment by KoditkarVedant** [comment]
@joemcbride I have changed my branch name and recreated the PR. Can you please have look at it?

**Comment by johnrutherford** [comment]
Yeah, I had also noticed that test was flaky. It should be fixed in PR #808.

**Comment by KoditkarVedant** [comment]
@joemcbride Friendly ping.

**Comment by sparamasivan** [comment]
My POCO has ulong fields. Can anyone help me on how to consume the same in custom implementation of ObjectGraphType? When the field is of type long it is not a problem but unsigned integer/long is a problem. 

I upgraded to GraphQL 2.4.0, still it is an issue.

**Pull request merged**
