### PR TITLE
Added maxBatchSize to DataLoaderContextExtensions

### PR DESCRIPTION
**Pull request by Rensvind**
Since maxBatchSize has been added to DataLoaderBase I added it to DataLoaderContextExtensions to ease usage of it.

### CODE REVIEW

**Comment by Shane32** [comment]
Looks good.  You need to update the apiapprovals file however.  Run the tests; one will fail.  Delete the applicable `approved` file and rename the `received` file to `approved`.  Run the tests again and it should pass.  Then commit the change

**Review by sungam3r — CHANGES_REQUESTED** [review]
It is still binary breaking changes. I'm OK with such changes but it should target develop branch.

**Comment by Rensvind** [comment]
I hope I got it right this time.

**Comment by Shane32** [comment]
@sungam3r Are you sure this is a breaking change?  They are static methods that cannot be inherited.

**Comment by Shane32** [comment]
@Rensvind Can you merge from develop again?

**Comment by sungam3r** [comment]
@Shane32 Imagine I wrote a library that uses these estension methods. Then some application uses my library (compiled code, nuget package, not source code). This application then updates the version of the dependency (GraphQL.NET) because it sees a minor/patch version change. As a result, an `MissingMethodException` exception will be thrown. Adding default parameter is backward compatible only for source code, but not to compiled one.

**Comment by Shane32** [comment]
Ok; that's probably why Microsoft rarely uses optional parameters in their method signatures.

**Comment by sungam3r** [comment]
> I hope I got it right this time.

Your PR contains extra commits from other contributors. Please rebase your branch onto develop and then force-push. Then you get the only one commit - your.

**Comment by Shane32** [comment]
I merged the prior commits from master into develop, so if he merges from develop again, it should merge in the merge commit which will clean up the history.

**Review by Shane32 — APPROVED** [review]

**Comment by Rensvind** [comment]
Thanks for being so patient with me, my git skills are non-existent 🙂

**Pull request merged**
