### PR TITLE
Description from xml documentation

### LINKED ISSUE #1124: Get descriptions from xml comments for AutoRegisteringObjectGraphType<T> and EnumerationGraphType<TEnum>
Further improvement for AutoRegisteringObjectGraphType / EnumerationGraphType - descriptions for the relevant fields can be taken from the xml comment file if it exists.

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #1124

### CODE REVIEW

**Comment by sungam3r** [comment]
Relates to #1163

**Comment by sungam3r** [comment]
Now descriptions from xml documentation by default are obtained for all GraphTypes which use `Description()` extension method, not just `AutoRegisteringObjectGraphType` / `EnumerationGraphType<TEnum>`.

**Comment by sungam3r** [comment]
@joemcbride Can this be merged? With the exception of cosmetic edits (`this.` deleted), the change is local. Backward compatibility is also not affected. The only thing that consumers can notice is the appearance of documentation where it was not there before.

**Comment by mikelneo** [comment]
Really waiting for this changes. hope it will be merged soon.

**Pull request merged**
