### PR TITLE
Fix SerializeList code

### LINKED ISSUE #4040: Fail to serialize list of strings into `ListGraphType<IdGraphType>`
Caused by 
- #4001

```c#
Field<ListGraphType<IdGraphType>>("test").Resolve(_ => new[] { "a", "b" });
```

Fails with exception
> System.NotSupportedException: Specified method is not supported.
   at GraphQL.Types.IdGraphType.SerializeList(IEnumerable list) in /_/src/GraphQL/Types/Scalars/IdGraphType.cs:line 101
   at GraphQL.Execution.ExecutionStrategy.SetArrayItemNodesAsync(ExecutionContext context, ArrayExecutionNode parent) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 430
   at GraphQL.Execution.ExecutionStrategy.CompleteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 587

### PR DESCRIPTION
**Pull request by Shane32**
Closes #4040

### CODE REVIEW

**Comment by Shane32** [comment]
Pfff.  `CanSerializeList` doesn't even work properly.  That's what you get when I don't write sufficient tests, I guess.

**Comment by gao-artur** [comment]
Wow! That's what you call sufficient tests? 😆

**Review by gao-artur — APPROVED** [review]

**Comment by Shane32** [comment]
This is rather critical code.

**Comment by gao-artur** [comment]
I think it would be better to improve the error message too. The`System.NotSupportedException: Specified method is not supported` wasn't very friendly and it took time to find out what exactly failed.

**Comment by Shane32** [comment]
> I think it would be better to improve the error message too. The`System.NotSupportedException: Specified method is not supported` wasn't very friendly and it took time to find out what exactly failed.

True, but it shouldn’t be possible to reach that line of code under any circumstances.

**Pull request merged**
