### PR TITLE
Introdude raw string literals

### PR DESCRIPTION
**Pull request by sungam3r**
I found [raw string literals](https://devblogs.microsoft.com/dotnet/csharp-11-preview-updates/) very useful. Only tests changed. VS 17.4 even highlights contents of raw string literals if this literal represents json.
изображение

### CODE REVIEW

**Comment by sungam3r** [comment]
Of course I changed only some little percent of all literals in tests.

**Review by Shane32 — APPROVED** [review]
I don't mind if you want to switch to raw string literals.  Not really a concern to me either; I'd rather invest time into functional changes.

Note: I didn't fully review this code; so let me know if there's any other changes made

**Comment by sungam3r** [comment]
Raw literals allow to write pure json (+ highlighting) and graphql (no highlighting) text without escaping.

**Comment by sungam3r** [comment]
I did not change any files out of tests.

**Pull request merged**
