### PR TITLE
Move all ResolveFieldContext classes and interfaces from GraphQL.Types namespace into GraphQL namespace

### PR DESCRIPTION
**Pull request by sungam3r**
Also a few code style rules applied.

### CODE REVIEW

**Comment by sungam3r** [comment]
These are breaking changes but I'm sure it’s worth making them in order to group APIs correctly. In addition, with high probability, customers will only need to recompile the code, and in the worst case, add some usings.

**Comment by Shane32** [comment]
These changes will be convenient for implementers.  Better to get it in now before 3.0 drops and add it to the upgrade guide.

**Comment by sungam3r** [comment]
I'm thinking of making red `BREAKING` label. What do you think?

**Comment by Shane32** [comment]
If you're asking me, that's a good idea.  It will be a lot easier to keep track of breaking changes post-3.0.

**Comment by sungam3r** [comment]
done

**Pull request merged**
