### PR TITLE
Merge branch 'master' of github.com:graphql-dotnet/graphql-dotnet into develop

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Comment by Shane32** [comment]
I'll perform the merge manually as we do not want squash and merge.

**Comment by Shane32** [comment]
I also need to back-merge the benchmark fix.  Give me a second

**Comment by sungam3r** [comment]
Should I close this?

**Comment by sungam3r** [comment]
Do you directly push into `develop` without PR? What about branch protection rules then?

**Comment by Shane32** [comment]
> Do you directly push into `develop` without PR? What about branch protection rules then?

Yes.  They are ignored.

Merged.

**Comment by Shane32** [comment]
I do run tests locally before pushing to be sure (as much as I can) that it merges okay.

**Comment by sungam3r** [comment]
OK

**Comment by Shane32** [comment]
> I also need to back-merge the benchmark fix. Give me a second

I'm guessing you already included the fixes.  It wouldn't let me do it.  (I was trying to cherry-pick #2137 from develop into master)

**Pull request closed without merging**
